// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package pgdbgen

import (
	"context"
	"database/sql"
)

const allChunksInOrder = `-- name: AllChunksInOrder :many
SELECT id, heading_path, text FROM chunks
 WHERE doc_id = $1 ORDER BY ordinal
`

type AllChunksInOrderRow struct {
	ID          int64
	HeadingPath string
	Text        string
}

func (q *Queries) AllChunksInOrder(ctx context.Context, docID string) ([]AllChunksInOrderRow, error) {
	rows, err := q.db.QueryContext(ctx, allChunksInOrder, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllChunksInOrderRow{}
	for rows.Next() {
		var i AllChunksInOrderRow
		if err := rows.Scan(&i.ID, &i.HeadingPath, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chunkOrdinal = `-- name: ChunkOrdinal :one
SELECT ordinal FROM chunks WHERE id = $1 AND doc_id = $2
`

type ChunkOrdinalParams struct {
	ID    int64
	DocID string
}

func (q *Queries) ChunkOrdinal(ctx context.Context, arg ChunkOrdinalParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, chunkOrdinal, arg.ID, arg.DocID)
	var ordinal int32
	err := row.Scan(&ordinal)
	return ordinal, err
}

const chunksInSection = `-- name: ChunksInSection :many
SELECT heading_path, text FROM chunks
 WHERE doc_id = $1 AND (chunks.section = $2 OR chunks.section LIKE $2 || '.%')
 ORDER BY ordinal
`

type ChunksInSectionParams struct {
	DocID   string
	Section sql.NullString
}

type ChunksInSectionRow struct {
	HeadingPath string
	Text        string
}

// Section references resolve component-wise, never by bare string prefix: a
// reference to "4" covers "4" and "4.1" and must not touch "41". The trailing
// dot is what makes it a boundary. Kept identical to store.SectionCovers,
// which the in-memory index-term boost applies by the same rule.
func (q *Queries) ChunksInSection(ctx context.Context, arg ChunksInSectionParams) ([]ChunksInSectionRow, error) {
	rows, err := q.db.QueryContext(ctx, chunksInSection, arg.DocID, arg.Section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChunksInSectionRow{}
	for rows.Next() {
		var i ChunksInSectionRow
		if err := rows.Scan(&i.HeadingPath, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chunksMatchingHeading = `-- name: ChunksMatchingHeading :many
SELECT heading_path, text FROM chunks
 WHERE doc_id = $1 AND lower(heading_path) LIKE '%' || lower($2) || '%'
 ORDER BY ordinal
`

type ChunksMatchingHeadingParams struct {
	DocID string
	Lower string
}

type ChunksMatchingHeadingRow struct {
	HeadingPath string
	Text        string
}

func (q *Queries) ChunksMatchingHeading(ctx context.Context, arg ChunksMatchingHeadingParams) ([]ChunksMatchingHeadingRow, error) {
	rows, err := q.db.QueryContext(ctx, chunksMatchingHeading, arg.DocID, arg.Lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChunksMatchingHeadingRow{}
	for rows.Next() {
		var i ChunksMatchingHeadingRow
		if err := rows.Scan(&i.HeadingPath, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contextChunks = `-- name: ContextChunks :many
SELECT id, ordinal, heading_path, section, page_start, image_count, url, fragment, text
  FROM chunks
 WHERE doc_id = $1 AND ordinal >= $2 AND ordinal <= $3
 ORDER BY ordinal
`

type ContextChunksParams struct {
	DocID     string
	Ordinal   int32
	Ordinal_2 int32
}

type ContextChunksRow struct {
	ID          int64
	Ordinal     int32
	HeadingPath string
	Section     sql.NullString
	PageStart   sql.NullInt32
	ImageCount  int32
	Url         sql.NullString
	Fragment    sql.NullString
	Text        string
}

func (q *Queries) ContextChunks(ctx context.Context, arg ContextChunksParams) ([]ContextChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, contextChunks, arg.DocID, arg.Ordinal, arg.Ordinal_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextChunksRow{}
	for rows.Next() {
		var i ContextChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.Ordinal,
			&i.HeadingPath,
			&i.Section,
			&i.PageStart,
			&i.ImageCount,
			&i.Url,
			&i.Fragment,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outlineRows = `-- name: OutlineRows :many
SELECT id, section, page_start, heading_path
  FROM chunks WHERE doc_id = $1 ORDER BY ordinal
`

type OutlineRowsRow struct {
	ID          int64
	Section     sql.NullString
	PageStart   sql.NullInt32
	HeadingPath string
}

func (q *Queries) OutlineRows(ctx context.Context, docID string) ([]OutlineRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, outlineRows, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutlineRowsRow{}
	for rows.Next() {
		var i OutlineRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.PageStart,
			&i.HeadingPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pagesInRange = `-- name: PagesInRange :many
SELECT page, text FROM pages
 WHERE doc_id = $1 AND page >= $2 AND page <= $3
 ORDER BY page
`

type PagesInRangeParams struct {
	DocID  string
	Page   int32
	Page_2 int32
}

type PagesInRangeRow struct {
	Page int32
	Text string
}

func (q *Queries) PagesInRange(ctx context.Context, arg PagesInRangeParams) ([]PagesInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, pagesInRange, arg.DocID, arg.Page, arg.Page_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PagesInRangeRow{}
	for rows.Next() {
		var i PagesInRangeRow
		if err := rows.Scan(&i.Page, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topLevelHeadings = `-- name: TopLevelHeadings :many

SELECT DISTINCT heading_path, ordinal FROM chunks
 WHERE doc_id = $1 AND heading_path <> ''
 ORDER BY ordinal
`

type TopLevelHeadingsRow struct {
	HeadingPath string
	Ordinal     int32
}

// Chunk and page reads, through internal/repository/postgres.
//
// Every statement runs in a transaction that named its user, so none of
// these filters on user_id: row-level security is where the library is
// chosen.
func (q *Queries) TopLevelHeadings(ctx context.Context, docID string) ([]TopLevelHeadingsRow, error) {
	rows, err := q.db.QueryContext(ctx, topLevelHeadings, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopLevelHeadingsRow{}
	for rows.Next() {
		var i TopLevelHeadingsRow
		if err := rows.Scan(&i.HeadingPath, &i.Ordinal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
