// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: docsearch/ingest/v1/ingest.proto

// Package docsearch.ingest.v1 is the typed door onto one ingest.
//
// Claude speaks MCP and cannot be asked to speak anything else, so MCP stays.
// Every other client gets this instead of hand-built HTTP: the `docsearch`
// CLI, `docsearch-sync` beside Paperless, and any later web UI through
// Connect-Web.
//
// File bytes never travel in a message. An upload is a plain HTTP PUT to a
// signed link, and the URL of what was uploaded is what arrives here.

package ingestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Quality grades a document's derived structure. The numbering matches
// docsearch's own enum, so the conversion at this boundary is a checked cast
// rather than a lookup table that can drift.
type Quality int32

const (
	Quality_QUALITY_UNSPECIFIED Quality = 0
	Quality_QUALITY_OK          Quality = 1
	Quality_QUALITY_DEGRADED    Quality = 2
	Quality_QUALITY_FAILED      Quality = 3
)

// Enum value maps for Quality.
var (
	Quality_name = map[int32]string{
		0: "QUALITY_UNSPECIFIED",
		1: "QUALITY_OK",
		2: "QUALITY_DEGRADED",
		3: "QUALITY_FAILED",
	}
	Quality_value = map[string]int32{
		"QUALITY_UNSPECIFIED": 0,
		"QUALITY_OK":          1,
		"QUALITY_DEGRADED":    2,
		"QUALITY_FAILED":      3,
	}
)

func (x Quality) Enum() *Quality {
	p := new(Quality)
	*p = x
	return p
}

func (x Quality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Quality) Descriptor() protoreflect.EnumDescriptor {
	return file_docsearch_ingest_v1_ingest_proto_enumTypes[0].Descriptor()
}

func (Quality) Type() protoreflect.EnumType {
	return &file_docsearch_ingest_v1_ingest_proto_enumTypes[0]
}

func (x Quality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Quality.Descriptor instead.
func (Quality) EnumDescriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_ingest_proto_rawDescGZIP(), []int{0}
}

// SourceKind says what a document was read from.
type SourceKind int32

const (
	SourceKind_SOURCE_KIND_UNSPECIFIED SourceKind = 0
	SourceKind_SOURCE_KIND_FILE        SourceKind = 1
	SourceKind_SOURCE_KIND_SITE        SourceKind = 2
)

// Enum value maps for SourceKind.
var (
	SourceKind_name = map[int32]string{
		0: "SOURCE_KIND_UNSPECIFIED",
		1: "SOURCE_KIND_FILE",
		2: "SOURCE_KIND_SITE",
	}
	SourceKind_value = map[string]int32{
		"SOURCE_KIND_UNSPECIFIED": 0,
		"SOURCE_KIND_FILE":        1,
		"SOURCE_KIND_SITE":        2,
	}
)

func (x SourceKind) Enum() *SourceKind {
	p := new(SourceKind)
	*p = x
	return p
}

func (x SourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_docsearch_ingest_v1_ingest_proto_enumTypes[1].Descriptor()
}

func (SourceKind) Type() protoreflect.EnumType {
	return &file_docsearch_ingest_v1_ingest_proto_enumTypes[1]
}

func (x SourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceKind.Descriptor instead.
func (SourceKind) EnumDescriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_ingest_proto_rawDescGZIP(), []int{1}
}

// Phase names the stage a progress report describes.
type Phase int32

const (
	Phase_PHASE_UNSPECIFIED Phase = 0
	Phase_PHASE_DISCOVER    Phase = 1
	Phase_PHASE_FETCH       Phase = 2
	Phase_PHASE_EXTRACT     Phase = 3
	Phase_PHASE_CHUNK       Phase = 4
	Phase_PHASE_INDEX       Phase = 5
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PHASE_DISCOVER",
		2: "PHASE_FETCH",
		3: "PHASE_EXTRACT",
		4: "PHASE_CHUNK",
		5: "PHASE_INDEX",
	}
	Phase_value = map[string]int32{
		"PHASE_UNSPECIFIED": 0,
		"PHASE_DISCOVER":    1,
		"PHASE_FETCH":       2,
		"PHASE_EXTRACT":     3,
		"PHASE_CHUNK":       4,
		"PHASE_INDEX":       5,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_docsearch_ingest_v1_ingest_proto_enumTypes[2].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_docsearch_ingest_v1_ingest_proto_enumTypes[2]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_ingest_proto_rawDescGZIP(), []int{2}
}

// Outcome says what an ingest did to the index.
type Outcome int32

const (
	Outcome_OUTCOME_UNSPECIFIED Outcome = 0
	// Ingested is a document the index did not hold.
	Outcome_OUTCOME_INGESTED Outcome = 1
	// Replaced is a document re-read at an address the index already held.
	Outcome_OUTCOME_REPLACED Outcome = 2
	// Unchanged is a source whose bytes are already indexed, under whatever
	// address they were first read from.
	Outcome_OUTCOME_UNCHANGED Outcome = 3
)

// Enum value maps for Outcome.
var (
	Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_INGESTED",
		2: "OUTCOME_REPLACED",
		3: "OUTCOME_UNCHANGED",
	}
	Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_INGESTED":    1,
		"OUTCOME_REPLACED":    2,
		"OUTCOME_UNCHANGED":   3,
	}
)

func (x Outcome) Enum() *Outcome {
	p := new(Outcome)
	*p = x
	return p
}

func (x Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_docsearch_ingest_v1_ingest_proto_enumTypes[3].Descriptor()
}

func (Outcome) Type() protoreflect.EnumType {
	return &file_docsearch_ingest_v1_ingest_proto_enumTypes[3]
}

func (x Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Outcome.Descriptor instead.
func (Outcome) EnumDescriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_ingest_proto_rawDescGZIP(), []int{3}
}

// IngestRequest names one source to read.
type IngestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source is a path inside the configured library root, or the URL of a
	// documentation site.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Title overrides the name the document is given. Empty takes the name the
	// document gives itself.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Revalidate false re-chunks an already-crawled site without a single
	// request. Ignored for a file.
	Revalidate    bool `protobuf:"varint,3,opt,name=revalidate,proto3" json:"revalidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_docsearch_ingest_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IngestRequest) GetRevalidate() bool {
	if x != nil {
		return x.Revalidate
	}
	return false
}

// Progress reports how far one phase has got.
type Progress struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Phase   Phase                  `protobuf:"varint,1,opt,name=phase,proto3,enum=docsearch.ingest.v1.Phase" json:"phase,omitempty"`
	Current int64                  `protobuf:"varint,2,opt,name=current,proto3" json:"current,omitempty"`
	// Total is 0 where nothing knows the total yet, which is ordinary while a
	// crawl is still discovering pages.
	Total         int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_docsearch_ingest_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *Progress) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNSPECIFIED
}

func (x *Progress) GetCurrent() int64 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *Progress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Result is what one ingest did, sent once, last.
type Result struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DocId      string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Title      string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ChunkCount int64                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Outcome    Outcome                `protobuf:"varint,4,opt,name=outcome,proto3,enum=docsearch.ingest.v1.Outcome" json:"outcome,omitempty"`
	// Note explains an outcome the caller did not ask for, and is empty where
	// the outcome speaks for itself.
	Note       string     `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	Quality    Quality    `protobuf:"varint,6,opt,name=quality,proto3,enum=docsearch.ingest.v1.Quality" json:"quality,omitempty"`
	SourceKind SourceKind `protobuf:"varint,7,opt,name=source_kind,json=sourceKind,proto3,enum=docsearch.ingest.v1.SourceKind" json:"source_kind,omitempty"`
	// Warnings is the structure report as it is persisted, so a client can show
	// what `docsearch verify` would show without asking again.
	Warnings      string `protobuf:"bytes,8,opt,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_docsearch_ingest_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Result) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Result) GetChunkCount() int64 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *Result) GetOutcome() Outcome {
	if x != nil {
		return x.Outcome
	}
	return Outcome_OUTCOME_UNSPECIFIED
}

func (x *Result) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Result) GetQuality() Quality {
	if x != nil {
		return x.Quality
	}
	return Quality_QUALITY_UNSPECIFIED
}

func (x *Result) GetSourceKind() SourceKind {
	if x != nil {
		return x.SourceKind
	}
	return SourceKind_SOURCE_KIND_UNSPECIFIED
}

func (x *Result) GetWarnings() string {
	if x != nil {
		return x.Warnings
	}
	return ""
}

// IngestResponse is one message of the stream: progress while the ingest
// runs, and the result once.
type IngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*IngestResponse_Progress
	//	*IngestResponse_Result
	Message       isIngestResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_docsearch_ingest_v1_ingest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_ingest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_ingest_proto_rawDescGZIP(), []int{3}
}

func (x *IngestResponse) GetMessage() isIngestResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *IngestResponse) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Message.(*IngestResponse_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *IngestResponse) GetResult() *Result {
	if x != nil {
		if x, ok := x.Message.(*IngestResponse_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isIngestResponse_Message interface {
	isIngestResponse_Message()
}

type IngestResponse_Progress struct {
	Progress *Progress `protobuf:"bytes,1,opt,name=progress,proto3,oneof"`
}

type IngestResponse_Result struct {
	Result *Result `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*IngestResponse_Progress) isIngestResponse_Message() {}

func (*IngestResponse_Result) isIngestResponse_Message() {}

var File_docsearch_ingest_v1_ingest_proto protoreflect.FileDescriptor

const file_docsearch_ingest_v1_ingest_proto_rawDesc = "" +
	"\n" +
	" docsearch/ingest/v1/ingest.proto\x12\x13docsearch.ingest.v1\"]\n" +
	"\rIngestRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"revalidate\x18\x03 \x01(\bR\n" +
	"revalidate\"l\n" +
	"\bProgress\x120\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x1a.docsearch.ingest.v1.PhaseR\x05phase\x12\x18\n" +
	"\acurrent\x18\x02 \x01(\x03R\acurrent\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xb8\x02\n" +
	"\x06Result\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x03R\n" +
	"chunkCount\x126\n" +
	"\aoutcome\x18\x04 \x01(\x0e2\x1c.docsearch.ingest.v1.OutcomeR\aoutcome\x12\x12\n" +
	"\x04note\x18\x05 \x01(\tR\x04note\x126\n" +
	"\aquality\x18\x06 \x01(\x0e2\x1c.docsearch.ingest.v1.QualityR\aquality\x12@\n" +
	"\vsource_kind\x18\a \x01(\x0e2\x1f.docsearch.ingest.v1.SourceKindR\n" +
	"sourceKind\x12\x1a\n" +
	"\bwarnings\x18\b \x01(\tR\bwarnings\"\x8f\x01\n" +
	"\x0eIngestResponse\x12;\n" +
	"\bprogress\x18\x01 \x01(\v2\x1d.docsearch.ingest.v1.ProgressH\x00R\bprogress\x125\n" +
	"\x06result\x18\x02 \x01(\v2\x1b.docsearch.ingest.v1.ResultH\x00R\x06resultB\t\n" +
	"\amessage*\\\n" +
	"\aQuality\x12\x17\n" +
	"\x13QUALITY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"QUALITY_OK\x10\x01\x12\x14\n" +
	"\x10QUALITY_DEGRADED\x10\x02\x12\x12\n" +
	"\x0eQUALITY_FAILED\x10\x03*U\n" +
	"\n" +
	"SourceKind\x12\x1b\n" +
	"\x17SOURCE_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SOURCE_KIND_FILE\x10\x01\x12\x14\n" +
	"\x10SOURCE_KIND_SITE\x10\x02*x\n" +
	"\x05Phase\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePHASE_DISCOVER\x10\x01\x12\x0f\n" +
	"\vPHASE_FETCH\x10\x02\x12\x11\n" +
	"\rPHASE_EXTRACT\x10\x03\x12\x0f\n" +
	"\vPHASE_CHUNK\x10\x04\x12\x0f\n" +
	"\vPHASE_INDEX\x10\x05*e\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OUTCOME_INGESTED\x10\x01\x12\x14\n" +
	"\x10OUTCOME_REPLACED\x10\x02\x12\x15\n" +
	"\x11OUTCOME_UNCHANGED\x10\x032f\n" +
	"\rIngestService\x12U\n" +
	"\x06Ingest\x12\".docsearch.ingest.v1.IngestRequest\x1a#.docsearch.ingest.v1.IngestResponse\"\x000\x01B\xdf\x01\n" +
	"\x17com.docsearch.ingest.v1B\vIngestProtoP\x01ZIgithub.com/bamsammich/docsearch/internal/api/docsearch/ingest/v1;ingestv1\xa2\x02\x03DIX\xaa\x02\x13Docsearch.Ingest.V1\xca\x02\x13Docsearch\\Ingest\\V1\xe2\x02\x1fDocsearch\\Ingest\\V1\\GPBMetadata\xea\x02\x15Docsearch::Ingest::V1b\x06proto3"

var (
	file_docsearch_ingest_v1_ingest_proto_rawDescOnce sync.Once
	file_docsearch_ingest_v1_ingest_proto_rawDescData []byte
)

func file_docsearch_ingest_v1_ingest_proto_rawDescGZIP() []byte {
	file_docsearch_ingest_v1_ingest_proto_rawDescOnce.Do(func() {
		file_docsearch_ingest_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docsearch_ingest_v1_ingest_proto_rawDesc), len(file_docsearch_ingest_v1_ingest_proto_rawDesc)))
	})
	return file_docsearch_ingest_v1_ingest_proto_rawDescData
}

var file_docsearch_ingest_v1_ingest_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_docsearch_ingest_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_docsearch_ingest_v1_ingest_proto_goTypes = []any{
	(Quality)(0),           // 0: docsearch.ingest.v1.Quality
	(SourceKind)(0),        // 1: docsearch.ingest.v1.SourceKind
	(Phase)(0),             // 2: docsearch.ingest.v1.Phase
	(Outcome)(0),           // 3: docsearch.ingest.v1.Outcome
	(*IngestRequest)(nil),  // 4: docsearch.ingest.v1.IngestRequest
	(*Progress)(nil),       // 5: docsearch.ingest.v1.Progress
	(*Result)(nil),         // 6: docsearch.ingest.v1.Result
	(*IngestResponse)(nil), // 7: docsearch.ingest.v1.IngestResponse
}
var file_docsearch_ingest_v1_ingest_proto_depIdxs = []int32{
	2, // 0: docsearch.ingest.v1.Progress.phase:type_name -> docsearch.ingest.v1.Phase
	3, // 1: docsearch.ingest.v1.Result.outcome:type_name -> docsearch.ingest.v1.Outcome
	0, // 2: docsearch.ingest.v1.Result.quality:type_name -> docsearch.ingest.v1.Quality
	1, // 3: docsearch.ingest.v1.Result.source_kind:type_name -> docsearch.ingest.v1.SourceKind
	5, // 4: docsearch.ingest.v1.IngestResponse.progress:type_name -> docsearch.ingest.v1.Progress
	6, // 5: docsearch.ingest.v1.IngestResponse.result:type_name -> docsearch.ingest.v1.Result
	4, // 6: docsearch.ingest.v1.IngestService.Ingest:input_type -> docsearch.ingest.v1.IngestRequest
	7, // 7: docsearch.ingest.v1.IngestService.Ingest:output_type -> docsearch.ingest.v1.IngestResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_docsearch_ingest_v1_ingest_proto_init() }
func file_docsearch_ingest_v1_ingest_proto_init() {
	if File_docsearch_ingest_v1_ingest_proto != nil {
		return
	}
	file_docsearch_ingest_v1_ingest_proto_msgTypes[3].OneofWrappers = []any{
		(*IngestResponse_Progress)(nil),
		(*IngestResponse_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docsearch_ingest_v1_ingest_proto_rawDesc), len(file_docsearch_ingest_v1_ingest_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docsearch_ingest_v1_ingest_proto_goTypes,
		DependencyIndexes: file_docsearch_ingest_v1_ingest_proto_depIdxs,
		EnumInfos:         file_docsearch_ingest_v1_ingest_proto_enumTypes,
		MessageInfos:      file_docsearch_ingest_v1_ingest_proto_msgTypes,
	}.Build()
	File_docsearch_ingest_v1_ingest_proto = out.File
	file_docsearch_ingest_v1_ingest_proto_goTypes = nil
	file_docsearch_ingest_v1_ingest_proto_depIdxs = nil
}
