// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: docsearch/ingest/v1/job.proto

// The ingest queue, which is the path a caller takes when it does not want
// to wait. IngestService.Ingest is the other one: it streams, and the caller
// watches.

package ingestv1

import (
	v1 "github.com/bamsammich/docsearch/internal/api/docsearch/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Job is one row of the queue.
type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	JobId int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Source is the path or URL the job names.
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	// Title overrides the name the document is given, and is empty where the
	// operator left it to name itself.
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// DocID is empty until the ingest settles on one, which it does before
	// writing anything, so a job that died mid-write still says what it was
	// writing.
	DocId string `protobuf:"bytes,4,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	// Status is 'queued', 'running', 'done', 'failed' or 'cancelled'.
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Phase and the progress pair are empty until the job is running.
	Phase           string `protobuf:"bytes,6,opt,name=phase,proto3" json:"phase,omitempty"`
	ProgressCurrent *int64 `protobuf:"varint,7,opt,name=progress_current,json=progressCurrent,proto3,oneof" json:"progress_current,omitempty"`
	ProgressTotal   *int64 `protobuf:"varint,8,opt,name=progress_total,json=progressTotal,proto3,oneof" json:"progress_total,omitempty"`
	Attempts        int64  `protobuf:"varint,9,opt,name=attempts,proto3" json:"attempts,omitempty"`
	// Permanent marks a failure another attempt would not survive, which is
	// what separates a job that failed deterministically from one that
	// exhausted its attempts.
	Permanent     bool       `protobuf:"varint,10,opt,name=permanent,proto3" json:"permanent,omitempty"`
	Error         string     `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	Quality       v1.Quality `protobuf:"varint,12,opt,name=quality,proto3,enum=docsearch.type.v1.Quality" json:"quality,omitempty"`
	Warnings      []string   `protobuf:"bytes,13,rep,name=warnings,proto3" json:"warnings,omitempty"`
	CreatedAt     string     `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string     `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *Job) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Job) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Job) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Job) GetProgressCurrent() int64 {
	if x != nil && x.ProgressCurrent != nil {
		return *x.ProgressCurrent
	}
	return 0
}

func (x *Job) GetProgressTotal() int64 {
	if x != nil && x.ProgressTotal != nil {
		return *x.ProgressTotal
	}
	return 0
}

func (x *Job) GetAttempts() int64 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Job) GetPermanent() bool {
	if x != nil {
		return x.Permanent
	}
	return false
}

func (x *Job) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Job) GetQuality() v1.Quality {
	if x != nil {
		return x.Quality
	}
	return v1.Quality(0)
}

func (x *Job) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *Job) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Job) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type EnqueueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source is a path inside the configured library root, or the URL of a
	// documentation site.
	Source        string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *EnqueueRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// QueuedJob is one job Enqueue created.
type QueuedJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Source is what this job will read, which is one of the files under the
	// directory the caller named rather than the directory itself.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	JobId  int64  `protobuf:"varint,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// Position counts the job itself, so a freshly queued job with nothing
	// ahead of it reports 1.
	QueuePosition int64 `protobuf:"varint,3,opt,name=queue_position,json=queuePosition,proto3" json:"queue_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuedJob) Reset() {
	*x = QueuedJob{}
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuedJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuedJob) ProtoMessage() {}

func (x *QueuedJob) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuedJob.ProtoReflect.Descriptor instead.
func (*QueuedJob) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *QueuedJob) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *QueuedJob) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *QueuedJob) GetQueuePosition() int64 {
	if x != nil {
		return x.QueuePosition
	}
	return 0
}

// EnqueueResponse names every job the request created, in the order they
// were queued, because a directory becomes one job per file beneath it and a
// caller that queued a library needs to see what it got.
type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*QueuedJob           `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *EnqueueResponse) GetJobs() []*QueuedJob {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type ListJobsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IncludeCompleted returns finished jobs as well as the queue.
	IncludeCompleted bool  `protobuf:"varint,1,opt,name=include_completed,json=includeCompleted,proto3" json:"include_completed,omitempty"`
	Limit            int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *ListJobsRequest) GetIncludeCompleted() bool {
	if x != nil {
		return x.IncludeCompleted
	}
	return false
}

func (x *ListJobsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *CancelJobRequest) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

type CancelJobResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Status is what the job reads as now. A job already finished is not
	// cancelled, and saying so beats reporting a cancellation that did
	// nothing.
	Status        string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_ingest_v1_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_docsearch_ingest_v1_job_proto_rawDescGZIP(), []int{7}
}

func (x *CancelJobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_docsearch_ingest_v1_job_proto protoreflect.FileDescriptor

const file_docsearch_ingest_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x1ddocsearch/ingest/v1/job.proto\x12\x13docsearch.ingest.v1\x1a\x1edocsearch/type/v1/common.proto\"\xf3\x03\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x15\n" +
	"\x06doc_id\x18\x04 \x01(\tR\x05docId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05phase\x18\x06 \x01(\tR\x05phase\x12.\n" +
	"\x10progress_current\x18\a \x01(\x03H\x00R\x0fprogressCurrent\x88\x01\x01\x12*\n" +
	"\x0eprogress_total\x18\b \x01(\x03H\x01R\rprogressTotal\x88\x01\x01\x12\x1a\n" +
	"\battempts\x18\t \x01(\x03R\battempts\x12\x1c\n" +
	"\tpermanent\x18\n" +
	" \x01(\bR\tpermanent\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x124\n" +
	"\aquality\x18\f \x01(\x0e2\x1a.docsearch.type.v1.QualityR\aquality\x12\x1a\n" +
	"\bwarnings\x18\r \x03(\tR\bwarnings\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\tR\tupdatedAtB\x13\n" +
	"\x11_progress_currentB\x11\n" +
	"\x0f_progress_total\">\n" +
	"\x0eEnqueueRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"a\n" +
	"\tQueuedJob\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\x03R\x05jobId\x12%\n" +
	"\x0equeue_position\x18\x03 \x01(\x03R\rqueuePosition\"Q\n" +
	"\x0fEnqueueResponse\x122\n" +
	"\x04jobs\x18\x03 \x03(\v2\x1e.docsearch.ingest.v1.QueuedJobR\x04jobsJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03\"T\n" +
	"\x0fListJobsRequest\x12+\n" +
	"\x11include_completed\x18\x01 \x01(\bR\x10includeCompleted\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"@\n" +
	"\x10ListJobsResponse\x12,\n" +
	"\x04jobs\x18\x01 \x03(\v2\x18.docsearch.ingest.v1.JobR\x04jobs\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\"+\n" +
	"\x11CancelJobResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x9d\x02\n" +
	"\n" +
	"JobService\x12V\n" +
	"\aEnqueue\x12#.docsearch.ingest.v1.EnqueueRequest\x1a$.docsearch.ingest.v1.EnqueueResponse\"\x00\x12Y\n" +
	"\bListJobs\x12$.docsearch.ingest.v1.ListJobsRequest\x1a%.docsearch.ingest.v1.ListJobsResponse\"\x00\x12\\\n" +
	"\tCancelJob\x12%.docsearch.ingest.v1.CancelJobRequest\x1a&.docsearch.ingest.v1.CancelJobResponse\"\x00B\xdc\x01\n" +
	"\x17com.docsearch.ingest.v1B\bJobProtoP\x01ZIgithub.com/bamsammich/docsearch/internal/api/docsearch/ingest/v1;ingestv1\xa2\x02\x03DIX\xaa\x02\x13Docsearch.Ingest.V1\xca\x02\x13Docsearch\\Ingest\\V1\xe2\x02\x1fDocsearch\\Ingest\\V1\\GPBMetadata\xea\x02\x15Docsearch::Ingest::V1b\x06proto3"

var (
	file_docsearch_ingest_v1_job_proto_rawDescOnce sync.Once
	file_docsearch_ingest_v1_job_proto_rawDescData []byte
)

func file_docsearch_ingest_v1_job_proto_rawDescGZIP() []byte {
	file_docsearch_ingest_v1_job_proto_rawDescOnce.Do(func() {
		file_docsearch_ingest_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docsearch_ingest_v1_job_proto_rawDesc), len(file_docsearch_ingest_v1_job_proto_rawDesc)))
	})
	return file_docsearch_ingest_v1_job_proto_rawDescData
}

var file_docsearch_ingest_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_docsearch_ingest_v1_job_proto_goTypes = []any{
	(*Job)(nil),               // 0: docsearch.ingest.v1.Job
	(*EnqueueRequest)(nil),    // 1: docsearch.ingest.v1.EnqueueRequest
	(*QueuedJob)(nil),         // 2: docsearch.ingest.v1.QueuedJob
	(*EnqueueResponse)(nil),   // 3: docsearch.ingest.v1.EnqueueResponse
	(*ListJobsRequest)(nil),   // 4: docsearch.ingest.v1.ListJobsRequest
	(*ListJobsResponse)(nil),  // 5: docsearch.ingest.v1.ListJobsResponse
	(*CancelJobRequest)(nil),  // 6: docsearch.ingest.v1.CancelJobRequest
	(*CancelJobResponse)(nil), // 7: docsearch.ingest.v1.CancelJobResponse
	(v1.Quality)(0),           // 8: docsearch.type.v1.Quality
}
var file_docsearch_ingest_v1_job_proto_depIdxs = []int32{
	8, // 0: docsearch.ingest.v1.Job.quality:type_name -> docsearch.type.v1.Quality
	2, // 1: docsearch.ingest.v1.EnqueueResponse.jobs:type_name -> docsearch.ingest.v1.QueuedJob
	0, // 2: docsearch.ingest.v1.ListJobsResponse.jobs:type_name -> docsearch.ingest.v1.Job
	1, // 3: docsearch.ingest.v1.JobService.Enqueue:input_type -> docsearch.ingest.v1.EnqueueRequest
	4, // 4: docsearch.ingest.v1.JobService.ListJobs:input_type -> docsearch.ingest.v1.ListJobsRequest
	6, // 5: docsearch.ingest.v1.JobService.CancelJob:input_type -> docsearch.ingest.v1.CancelJobRequest
	3, // 6: docsearch.ingest.v1.JobService.Enqueue:output_type -> docsearch.ingest.v1.EnqueueResponse
	5, // 7: docsearch.ingest.v1.JobService.ListJobs:output_type -> docsearch.ingest.v1.ListJobsResponse
	7, // 8: docsearch.ingest.v1.JobService.CancelJob:output_type -> docsearch.ingest.v1.CancelJobResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_docsearch_ingest_v1_job_proto_init() }
func file_docsearch_ingest_v1_job_proto_init() {
	if File_docsearch_ingest_v1_job_proto != nil {
		return
	}
	file_docsearch_ingest_v1_job_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docsearch_ingest_v1_job_proto_rawDesc), len(file_docsearch_ingest_v1_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docsearch_ingest_v1_job_proto_goTypes,
		DependencyIndexes: file_docsearch_ingest_v1_job_proto_depIdxs,
		MessageInfos:      file_docsearch_ingest_v1_job_proto_msgTypes,
	}.Build()
	File_docsearch_ingest_v1_job_proto = out.File
	file_docsearch_ingest_v1_job_proto_goTypes = nil
	file_docsearch_ingest_v1_job_proto_depIdxs = nil
}
