-- Version 5 on Postgres: the schema its SQLite twin in ../sqlite declares,
-- in the SQL a server speaks. The same version number because the schema
-- means the same thing; only the engine differs.
--
-- Still one library. Step 4b gives every row an owner, partitions chunks by
-- that owner and turns on row-level security, which is a restructuring this
-- baseline deliberately does not anticipate: a migration that moves existing
-- rows is worth testing, and writing the destination here would leave
-- nothing to test.
--
-- Two shapes changed with the engine. An integer key that SQLite filled from
-- the rowid is declared as an identity column, and the timestamps that were
-- TEXT are timestamptz, so comparing two of them orders them by time rather
-- than by string.
--
-- Full-text search is absent here. FTS5's virtual table and the three
-- triggers that fed it have no counterpart to port: step 4d indexes chunks
-- with pg_textsearch, which maintains itself.
--
-- +goose Up
-- +goose StatementBegin

CREATE TABLE documents (
  doc_id       text PRIMARY KEY,
  title        text NOT NULL,
  format       text NOT NULL,
  source_path  text NOT NULL,   -- absolute path, or the canonical base URL of a site
  source_kind  text NOT NULL DEFAULT 'file',  -- 'file' | 'site'
  sha256       text NOT NULL,
  page_count   integer,
  chunk_count  integer,
  status       text NOT NULL,
  ingested_at  timestamptz,
  warnings     text              -- JSON StructureReport; NULL until ingest completes
);
CREATE INDEX idx_documents_source ON documents(source_path);
CREATE INDEX idx_documents_sha    ON documents(sha256);

CREATE TABLE ingest_jobs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_path   text NOT NULL,
  title         text,
  doc_id        text,
  status        text NOT NULL,
  phase         text,
  progress_cur  integer,
  progress_tot  integer,
  attempts      integer NOT NULL DEFAULT 0,
  permanent     boolean NOT NULL DEFAULT false,  -- failed deterministically; never retried
  cancel_req    boolean NOT NULL DEFAULT false,
  error         text,
  warnings      text,
  lease_until   timestamptz,
  created_at    timestamptz NOT NULL,
  updated_at    timestamptz NOT NULL
);
CREATE INDEX idx_jobs_status ON ingest_jobs(status, created_at);

CREATE TABLE chunks (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id             text NOT NULL REFERENCES documents(doc_id),
  ordinal            integer NOT NULL,
  section            text,
  page_start         integer,
  page_end           integer,
  printed_page_start integer,
  image_count        integer NOT NULL DEFAULT 0,
  kind               text NOT NULL DEFAULT 'prose',
  url                text,             -- page this chunk was read from; NULL for local files
  fragment           text,             -- in-page anchor, without the leading '#'
  heading_path       text NOT NULL,
  text               text NOT NULL
);
CREATE INDEX idx_chunks_doc_ord     ON chunks(doc_id, ordinal);
CREATE INDEX idx_chunks_doc_section ON chunks(doc_id, section);

CREATE TABLE pages (
  doc_id text NOT NULL REFERENCES documents(doc_id),
  page   integer NOT NULL,
  text   text NOT NULL,
  PRIMARY KEY (doc_id, page)
);

CREATE TABLE index_terms (
  doc_id  text NOT NULL REFERENCES documents(doc_id),
  term    text NOT NULL,
  section text NOT NULL
);
CREATE INDEX idx_index_terms ON index_terms(doc_id, term);

CREATE TABLE schema_version (
  version     integer NOT NULL,
  applied_at  timestamptz NOT NULL
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- The tables that reference documents, then documents itself.
DROP TABLE IF EXISTS index_terms;
DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS chunks;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS ingest_jobs;
DROP TABLE IF EXISTS schema_version;
-- +goose StatementEnd
