-- Version 6: every row belongs to one user, and the database enforces it.
--
-- Authentication is phase 05, so one user exists and every request belongs
-- to it. Phase 05 adds an issuer and a subject to users and attaches real
-- identities to the same rows, which is why the identifier is a text key
-- the application chooses rather than a serial.
--
-- Three things make the isolation, and all three are needed. user_id on
-- every tenant table is what a policy can filter on. Partitioning chunks by
-- user is what keeps one user's statistics out of another's ranking, since
-- BM25's inverse document frequency and average length span an index:
-- docs/research/postgres-spike.md measured 14 of alice's results moving
-- when bob loaded three copies of one manual into a shared index. Row-level
-- security is what catches a query that forgot its filter.
--
-- FORCE is deliberate. Without it the table owner bypasses the policy, and
-- the owner is what migrations and the worker connect as, so the policy
-- would guard only the restricted role. With it every writer names the user
-- it writes for, which is the property the isolation test checks.
--
-- chunks is recreated rather than altered: a partitioned table cannot be
-- made from an existing one in place, and its primary key must contain the
-- partition key.
--
-- +goose Up
-- +goose StatementBegin

CREATE TABLE users (
  user_id    text PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- The one user phase 04 serves. Switching to a mode with accounts hands
-- this library to the first account created, so a single-user install
-- survives the move.
INSERT INTO users (user_id) VALUES ('default');

-- Each tenant table gains its owner, defaulted so the rows already there
-- belong to the one user that exists, and then pinned so a later insert
-- cannot omit it.
ALTER TABLE documents   ADD COLUMN user_id text NOT NULL DEFAULT 'default';
ALTER TABLE pages       ADD COLUMN user_id text NOT NULL DEFAULT 'default';
ALTER TABLE index_terms ADD COLUMN user_id text NOT NULL DEFAULT 'default';
ALTER TABLE ingest_jobs ADD COLUMN user_id text NOT NULL DEFAULT 'default';
ALTER TABLE documents   ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE pages       ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE index_terms ALTER COLUMN user_id DROP DEFAULT;
ALTER TABLE ingest_jobs ALTER COLUMN user_id DROP DEFAULT;

-- A doc_id is unique within one library rather than across all of them, so
-- the key gains the owner and every reference to it follows.
ALTER TABLE pages       DROP CONSTRAINT pages_doc_id_fkey;
ALTER TABLE index_terms DROP CONSTRAINT index_terms_doc_id_fkey;
ALTER TABLE chunks      DROP CONSTRAINT chunks_doc_id_fkey;
ALTER TABLE documents   DROP CONSTRAINT documents_pkey;
ALTER TABLE documents   ADD CONSTRAINT documents_pkey PRIMARY KEY (user_id, doc_id);
ALTER TABLE documents   ADD CONSTRAINT documents_user_fkey
  FOREIGN KEY (user_id) REFERENCES users(user_id);

ALTER TABLE pages DROP CONSTRAINT pages_pkey;
ALTER TABLE pages ADD CONSTRAINT pages_pkey PRIMARY KEY (user_id, doc_id, page);
ALTER TABLE pages ADD CONSTRAINT pages_doc_fkey
  FOREIGN KEY (user_id, doc_id) REFERENCES documents(user_id, doc_id);
ALTER TABLE index_terms ADD CONSTRAINT index_terms_doc_fkey
  FOREIGN KEY (user_id, doc_id) REFERENCES documents(user_id, doc_id);

-- chunks, partitioned by user. The rows move through a copy because no
-- ALTER makes a partitioned table out of a plain one.
ALTER TABLE chunks RENAME TO chunks_unpartitioned;
ALTER INDEX idx_chunks_doc_ord     RENAME TO idx_chunks_doc_ord_old;
ALTER INDEX idx_chunks_doc_section RENAME TO idx_chunks_doc_section_old;

CREATE TABLE chunks (
  user_id            text NOT NULL,
  id                 bigint GENERATED BY DEFAULT AS IDENTITY,
  doc_id             text NOT NULL,
  ordinal            integer NOT NULL,
  section            text,
  page_start         integer,
  page_end           integer,
  printed_page_start integer,
  image_count        integer NOT NULL DEFAULT 0,
  kind               text NOT NULL DEFAULT 'prose',
  url                text,
  fragment           text,
  heading_path       text NOT NULL,
  text               text NOT NULL,
  PRIMARY KEY (user_id, id),
  FOREIGN KEY (user_id, doc_id) REFERENCES documents(user_id, doc_id)
) PARTITION BY LIST (user_id);

CREATE TABLE chunks_default PARTITION OF chunks FOR VALUES IN ('default');

INSERT INTO chunks (
  user_id, id, doc_id, ordinal, section, page_start, page_end,
  printed_page_start, image_count, kind, url, fragment, heading_path, text)
SELECT 'default', id, doc_id, ordinal, section, page_start, page_end,
       printed_page_start, image_count, kind, url, fragment, heading_path, text
  FROM chunks_unpartitioned;

-- The identity column continues from the rows that moved, so a new chunk
-- cannot collide with one that came across.
SELECT setval(
  pg_get_serial_sequence('chunks', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 0) FROM chunks), 1));

DROP TABLE chunks_unpartitioned;
CREATE INDEX idx_chunks_doc_ord     ON chunks(user_id, doc_id, ordinal);
CREATE INDEX idx_chunks_doc_section ON chunks(user_id, doc_id, section);

-- Row-level security on every table that holds a user's rows. users itself
-- is not one: the application reads it to learn who exists, before any
-- request has said who it is.
ALTER TABLE documents   ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents   FORCE  ROW LEVEL SECURITY;
ALTER TABLE chunks      ENABLE ROW LEVEL SECURITY;
ALTER TABLE chunks      FORCE  ROW LEVEL SECURITY;
ALTER TABLE pages       ENABLE ROW LEVEL SECURITY;
ALTER TABLE pages       FORCE  ROW LEVEL SECURITY;
ALTER TABLE index_terms ENABLE ROW LEVEL SECURITY;
ALTER TABLE index_terms FORCE  ROW LEVEL SECURITY;
ALTER TABLE ingest_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingest_jobs FORCE  ROW LEVEL SECURITY;

-- One policy per table, covering reads and writes alike: a row a session
-- cannot see is also a row it cannot write. app.user_id is set at the start
-- of every transaction, and its absence matches nothing.
CREATE POLICY own ON documents   USING (user_id = current_setting('app.user_id', true))
  WITH CHECK (user_id = current_setting('app.user_id', true));
CREATE POLICY own ON chunks      USING (user_id = current_setting('app.user_id', true))
  WITH CHECK (user_id = current_setting('app.user_id', true));
CREATE POLICY own ON pages       USING (user_id = current_setting('app.user_id', true))
  WITH CHECK (user_id = current_setting('app.user_id', true));
CREATE POLICY own ON index_terms USING (user_id = current_setting('app.user_id', true))
  WITH CHECK (user_id = current_setting('app.user_id', true));
CREATE POLICY own ON ingest_jobs USING (user_id = current_setting('app.user_id', true))
  WITH CHECK (user_id = current_setting('app.user_id', true));

-- What the restricted role may do. It owns nothing, so every privilege it
-- has is one granted here, and row-level security decides which rows each
-- one reaches.
GRANT SELECT, INSERT, UPDATE, DELETE
  ON documents, chunks, pages, index_terms, ingest_jobs TO docsearch_app;
GRANT SELECT ON users TO docsearch_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO docsearch_app;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM docsearch_app;
REVOKE ALL ON users FROM docsearch_app;
REVOKE ALL ON documents, chunks, pages, index_terms, ingest_jobs FROM docsearch_app;

DROP POLICY own ON ingest_jobs;
DROP POLICY own ON index_terms;
DROP POLICY own ON pages;
DROP POLICY own ON chunks;
DROP POLICY own ON documents;
ALTER TABLE ingest_jobs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ingest_jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE index_terms NO FORCE ROW LEVEL SECURITY;
ALTER TABLE index_terms DISABLE ROW LEVEL SECURITY;
ALTER TABLE pages       NO FORCE ROW LEVEL SECURITY;
ALTER TABLE pages       DISABLE ROW LEVEL SECURITY;
ALTER TABLE chunks      NO FORCE ROW LEVEL SECURITY;
ALTER TABLE chunks      DISABLE ROW LEVEL SECURITY;
ALTER TABLE documents   NO FORCE ROW LEVEL SECURITY;
ALTER TABLE documents   DISABLE ROW LEVEL SECURITY;

-- chunks goes back to one table for everyone. Only the one user's rows can
-- survive, which is what going back to a single library means.
ALTER TABLE chunks RENAME TO chunks_partitioned;
ALTER INDEX idx_chunks_doc_ord     RENAME TO idx_chunks_doc_ord_part;
ALTER INDEX idx_chunks_doc_section RENAME TO idx_chunks_doc_section_part;

CREATE TABLE chunks (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id             text NOT NULL,
  ordinal            integer NOT NULL,
  section            text,
  page_start         integer,
  page_end           integer,
  printed_page_start integer,
  image_count        integer NOT NULL DEFAULT 0,
  kind               text NOT NULL DEFAULT 'prose',
  url                text,
  fragment           text,
  heading_path       text NOT NULL,
  text               text NOT NULL
);
INSERT INTO chunks (
  id, doc_id, ordinal, section, page_start, page_end, printed_page_start,
  image_count, kind, url, fragment, heading_path, text)
SELECT id, doc_id, ordinal, section, page_start, page_end, printed_page_start,
       image_count, kind, url, fragment, heading_path, text
  FROM chunks_partitioned WHERE user_id = 'default';
SELECT setval(
  pg_get_serial_sequence('chunks', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 0) FROM chunks), 1));
DROP TABLE chunks_partitioned;

ALTER TABLE index_terms DROP CONSTRAINT index_terms_doc_fkey;
ALTER TABLE pages       DROP CONSTRAINT pages_doc_fkey;
ALTER TABLE pages       DROP CONSTRAINT pages_pkey;
DELETE FROM pages       WHERE user_id <> 'default';
DELETE FROM index_terms WHERE user_id <> 'default';
DELETE FROM documents   WHERE user_id <> 'default';
DELETE FROM ingest_jobs WHERE user_id <> 'default';
ALTER TABLE pages ADD CONSTRAINT pages_pkey PRIMARY KEY (doc_id, page);

ALTER TABLE documents DROP CONSTRAINT documents_user_fkey;
ALTER TABLE documents DROP CONSTRAINT documents_pkey;
ALTER TABLE documents ADD CONSTRAINT documents_pkey PRIMARY KEY (doc_id);

ALTER TABLE chunks ADD CONSTRAINT chunks_doc_id_fkey
  FOREIGN KEY (doc_id) REFERENCES documents(doc_id);
ALTER TABLE pages ADD CONSTRAINT pages_doc_id_fkey
  FOREIGN KEY (doc_id) REFERENCES documents(doc_id);
ALTER TABLE index_terms ADD CONSTRAINT index_terms_doc_id_fkey
  FOREIGN KEY (doc_id) REFERENCES documents(doc_id);

ALTER TABLE ingest_jobs DROP COLUMN user_id;
ALTER TABLE index_terms DROP COLUMN user_id;
ALTER TABLE pages       DROP COLUMN user_id;
ALTER TABLE documents   DROP COLUMN user_id;
CREATE INDEX idx_chunks_doc_ord     ON chunks(doc_id, ordinal);
CREATE INDEX idx_chunks_doc_section ON chunks(doc_id, section);
DROP TABLE users;
-- +goose StatementEnd
