// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: docsearch/document/v1/document.proto

// Package docsearch.document.v1 answers questions about what the index
// already holds.
package documentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/bamsammich/docsearch/internal/api/docsearch/document/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DocumentServiceName is the fully-qualified name of the DocumentService service.
	DocumentServiceName = "docsearch.document.v1.DocumentService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DocumentServiceListProcedure is the fully-qualified name of the DocumentService's List RPC.
	DocumentServiceListProcedure = "/docsearch.document.v1.DocumentService/List"
	// DocumentServiceVerifyProcedure is the fully-qualified name of the DocumentService's Verify RPC.
	DocumentServiceVerifyProcedure = "/docsearch.document.v1.DocumentService/Verify"
	// DocumentServiceInspectProcedure is the fully-qualified name of the DocumentService's Inspect RPC.
	DocumentServiceInspectProcedure = "/docsearch.document.v1.DocumentService/Inspect"
	// DocumentServiceRemoveProcedure is the fully-qualified name of the DocumentService's Remove RPC.
	DocumentServiceRemoveProcedure = "/docsearch.document.v1.DocumentService/Remove"
)

// DocumentServiceClient is a client for the docsearch.document.v1.DocumentService service.
type DocumentServiceClient interface {
	// List is every ready document.
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	// Verify checks one stored document, both ways.
	Verify(context.Context, *connect.Request[v1.VerifyRequest]) (*connect.Response[v1.VerifyResponse], error)
	// Inspect reports what ingest would make of a target, writing nothing.
	//
	// A site is crawled for real, because every question worth asking about
	// one is a question about what the server returns.
	Inspect(context.Context, *connect.Request[v1.InspectRequest]) (*connect.Response[v1.InspectResponse], error)
	// Remove deletes a document from the index.
	Remove(context.Context, *connect.Request[v1.RemoveRequest]) (*connect.Response[v1.RemoveResponse], error)
}

// NewDocumentServiceClient constructs a client for the docsearch.document.v1.DocumentService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDocumentServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DocumentServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	documentServiceMethods := v1.File_docsearch_document_v1_document_proto.Services().ByName("DocumentService").Methods()
	return &documentServiceClient{
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+DocumentServiceListProcedure,
			connect.WithSchema(documentServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		verify: connect.NewClient[v1.VerifyRequest, v1.VerifyResponse](
			httpClient,
			baseURL+DocumentServiceVerifyProcedure,
			connect.WithSchema(documentServiceMethods.ByName("Verify")),
			connect.WithClientOptions(opts...),
		),
		inspect: connect.NewClient[v1.InspectRequest, v1.InspectResponse](
			httpClient,
			baseURL+DocumentServiceInspectProcedure,
			connect.WithSchema(documentServiceMethods.ByName("Inspect")),
			connect.WithClientOptions(opts...),
		),
		remove: connect.NewClient[v1.RemoveRequest, v1.RemoveResponse](
			httpClient,
			baseURL+DocumentServiceRemoveProcedure,
			connect.WithSchema(documentServiceMethods.ByName("Remove")),
			connect.WithClientOptions(opts...),
		),
	}
}

// documentServiceClient implements DocumentServiceClient.
type documentServiceClient struct {
	list    *connect.Client[v1.ListRequest, v1.ListResponse]
	verify  *connect.Client[v1.VerifyRequest, v1.VerifyResponse]
	inspect *connect.Client[v1.InspectRequest, v1.InspectResponse]
	remove  *connect.Client[v1.RemoveRequest, v1.RemoveResponse]
}

// List calls docsearch.document.v1.DocumentService.List.
func (c *documentServiceClient) List(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Verify calls docsearch.document.v1.DocumentService.Verify.
func (c *documentServiceClient) Verify(ctx context.Context, req *connect.Request[v1.VerifyRequest]) (*connect.Response[v1.VerifyResponse], error) {
	return c.verify.CallUnary(ctx, req)
}

// Inspect calls docsearch.document.v1.DocumentService.Inspect.
func (c *documentServiceClient) Inspect(ctx context.Context, req *connect.Request[v1.InspectRequest]) (*connect.Response[v1.InspectResponse], error) {
	return c.inspect.CallUnary(ctx, req)
}

// Remove calls docsearch.document.v1.DocumentService.Remove.
func (c *documentServiceClient) Remove(ctx context.Context, req *connect.Request[v1.RemoveRequest]) (*connect.Response[v1.RemoveResponse], error) {
	return c.remove.CallUnary(ctx, req)
}

// DocumentServiceHandler is an implementation of the docsearch.document.v1.DocumentService service.
type DocumentServiceHandler interface {
	// List is every ready document.
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	// Verify checks one stored document, both ways.
	Verify(context.Context, *connect.Request[v1.VerifyRequest]) (*connect.Response[v1.VerifyResponse], error)
	// Inspect reports what ingest would make of a target, writing nothing.
	//
	// A site is crawled for real, because every question worth asking about
	// one is a question about what the server returns.
	Inspect(context.Context, *connect.Request[v1.InspectRequest]) (*connect.Response[v1.InspectResponse], error)
	// Remove deletes a document from the index.
	Remove(context.Context, *connect.Request[v1.RemoveRequest]) (*connect.Response[v1.RemoveResponse], error)
}

// NewDocumentServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDocumentServiceHandler(svc DocumentServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	documentServiceMethods := v1.File_docsearch_document_v1_document_proto.Services().ByName("DocumentService").Methods()
	documentServiceListHandler := connect.NewUnaryHandler(
		DocumentServiceListProcedure,
		svc.List,
		connect.WithSchema(documentServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceVerifyHandler := connect.NewUnaryHandler(
		DocumentServiceVerifyProcedure,
		svc.Verify,
		connect.WithSchema(documentServiceMethods.ByName("Verify")),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceInspectHandler := connect.NewUnaryHandler(
		DocumentServiceInspectProcedure,
		svc.Inspect,
		connect.WithSchema(documentServiceMethods.ByName("Inspect")),
		connect.WithHandlerOptions(opts...),
	)
	documentServiceRemoveHandler := connect.NewUnaryHandler(
		DocumentServiceRemoveProcedure,
		svc.Remove,
		connect.WithSchema(documentServiceMethods.ByName("Remove")),
		connect.WithHandlerOptions(opts...),
	)
	return "/docsearch.document.v1.DocumentService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DocumentServiceListProcedure:
			documentServiceListHandler.ServeHTTP(w, r)
		case DocumentServiceVerifyProcedure:
			documentServiceVerifyHandler.ServeHTTP(w, r)
		case DocumentServiceInspectProcedure:
			documentServiceInspectHandler.ServeHTTP(w, r)
		case DocumentServiceRemoveProcedure:
			documentServiceRemoveHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDocumentServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDocumentServiceHandler struct{}

func (UnimplementedDocumentServiceHandler) List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("docsearch.document.v1.DocumentService.List is not implemented"))
}

func (UnimplementedDocumentServiceHandler) Verify(context.Context, *connect.Request[v1.VerifyRequest]) (*connect.Response[v1.VerifyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("docsearch.document.v1.DocumentService.Verify is not implemented"))
}

func (UnimplementedDocumentServiceHandler) Inspect(context.Context, *connect.Request[v1.InspectRequest]) (*connect.Response[v1.InspectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("docsearch.document.v1.DocumentService.Inspect is not implemented"))
}

func (UnimplementedDocumentServiceHandler) Remove(context.Context, *connect.Request[v1.RemoveRequest]) (*connect.Response[v1.RemoveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("docsearch.document.v1.DocumentService.Remove is not implemented"))
}
