// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: docsearch/document/v1/document.proto

// Package docsearch.document.v1 answers questions about what the index
// already holds.

package documentv1

import (
	v1 "github.com/bamsammich/docsearch/internal/api/docsearch/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document is one document the index holds.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	DocId string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Title string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Format is how the document was extracted; source_kind is where it came
	// from. A site is a site whatever its pages were parsed as.
	Format     string        `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	SourceKind v1.SourceKind `protobuf:"varint,4,opt,name=source_kind,json=sourceKind,proto3,enum=docsearch.type.v1.SourceKind" json:"source_kind,omitempty"`
	// Status is 'ingesting' or 'ready'. Every search path filters for ready,
	// so a document that is not is invisible to everything but verification.
	Status     string     `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	PageCount  *int64     `protobuf:"varint,6,opt,name=page_count,json=pageCount,proto3,oneof" json:"page_count,omitempty"`
	ChunkCount *int64     `protobuf:"varint,7,opt,name=chunk_count,json=chunkCount,proto3,oneof" json:"chunk_count,omitempty"`
	Quality    v1.Quality `protobuf:"varint,8,opt,name=quality,proto3,enum=docsearch.type.v1.Quality" json:"quality,omitempty"`
	// Warnings are the structure report's notes, as an operator reads them.
	Warnings      []string `protobuf:"bytes,9,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Document) GetSourceKind() v1.SourceKind {
	if x != nil {
		return x.SourceKind
	}
	return v1.SourceKind(0)
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Document) GetPageCount() int64 {
	if x != nil && x.PageCount != nil {
		return *x.PageCount
	}
	return 0
}

func (x *Document) GetChunkCount() int64 {
	if x != nil && x.ChunkCount != nil {
		return *x.ChunkCount
	}
	return 0
}

func (x *Document) GetQuality() v1.Quality {
	if x != nil {
		return x.Quality
	}
	return v1.Quality(0)
}

func (x *Document) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// TokenSpread is the distribution of a document's chunk sizes.
//
// Eyeballing it catches a structural extraction failure immediately: a
// heading source that silently collapsed shows up as a handful of enormous
// chunks, and a shattered one as hundreds of near-empty chunks.
type TokenSpread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           int64                  `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Median        int64                  `protobuf:"varint,2,opt,name=median,proto3" json:"median,omitempty"`
	P95           int64                  `protobuf:"varint,3,opt,name=p95,proto3" json:"p95,omitempty"`
	Max           int64                  `protobuf:"varint,4,opt,name=max,proto3" json:"max,omitempty"`
	Mean          int64                  `protobuf:"varint,5,opt,name=mean,proto3" json:"mean,omitempty"`
	Total         int64                  `protobuf:"varint,6,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSpread) Reset() {
	*x = TokenSpread{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSpread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSpread) ProtoMessage() {}

func (x *TokenSpread) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSpread.ProtoReflect.Descriptor instead.
func (*TokenSpread) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{1}
}

func (x *TokenSpread) GetMin() int64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *TokenSpread) GetMedian() int64 {
	if x != nil {
		return x.Median
	}
	return 0
}

func (x *TokenSpread) GetP95() int64 {
	if x != nil {
		return x.P95
	}
	return 0
}

func (x *TokenSpread) GetMax() int64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *TokenSpread) GetMean() int64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *TokenSpread) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// SizedChunk names one chunk by where it sits and how big it is.
type SizedChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordinal rather than a row id, so a reader can find the chunk in the
	// document.
	Ordinal       int64  `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Tokens        int64  `protobuf:"varint,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	HeadingPath   string `protobuf:"bytes,3,opt,name=heading_path,json=headingPath,proto3" json:"heading_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizedChunk) Reset() {
	*x = SizedChunk{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizedChunk) ProtoMessage() {}

func (x *SizedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizedChunk.ProtoReflect.Descriptor instead.
func (*SizedChunk) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{2}
}

func (x *SizedChunk) GetOrdinal() int64 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *SizedChunk) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

func (x *SizedChunk) GetHeadingPath() string {
	if x != nil {
		return x.HeadingPath
	}
	return ""
}

// Measurements are what a document's chunks show about how it was stored.
type Measurements struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ChunkCount int64                  `protobuf:"varint,1,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Tokens     *TokenSpread           `protobuf:"bytes,2,opt,name=tokens,proto3" json:"tokens,omitempty"`
	Longest    []*SizedChunk          `protobuf:"bytes,3,rep,name=longest,proto3" json:"longest,omitempty"`
	Shortest   []*SizedChunk          `protobuf:"bytes,4,rep,name=shortest,proto3" json:"shortest,omitempty"`
	// Pages of a paginated document that no chunk claims.
	UncoveredPages []int64 `protobuf:"varint,5,rep,packed,name=uncovered_pages,json=uncoveredPages,proto3" json:"uncovered_pages,omitempty"`
	// Where the chunk numbering skips, by the ordinal before each gap.
	OrdinalGaps []int64 `protobuf:"varint,6,rep,packed,name=ordinal_gaps,json=ordinalGaps,proto3" json:"ordinal_gaps,omitempty"`
	// Sections whose chunks are not contiguous.
	ScatteredSections []string `protobuf:"bytes,7,rep,name=scattered_sections,json=scatteredSections,proto3" json:"scattered_sections,omitempty"`
	// Chunks of a paginated document that name no page.
	MissingLocator   int64 `protobuf:"varint,8,opt,name=missing_locator,json=missingLocator,proto3" json:"missing_locator,omitempty"`
	ChunksWithImages int64 `protobuf:"varint,9,opt,name=chunks_with_images,json=chunksWithImages,proto3" json:"chunks_with_images,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Measurements) Reset() {
	*x = Measurements{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Measurements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Measurements) ProtoMessage() {}

func (x *Measurements) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Measurements.ProtoReflect.Descriptor instead.
func (*Measurements) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{3}
}

func (x *Measurements) GetChunkCount() int64 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *Measurements) GetTokens() *TokenSpread {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *Measurements) GetLongest() []*SizedChunk {
	if x != nil {
		return x.Longest
	}
	return nil
}

func (x *Measurements) GetShortest() []*SizedChunk {
	if x != nil {
		return x.Shortest
	}
	return nil
}

func (x *Measurements) GetUncoveredPages() []int64 {
	if x != nil {
		return x.UncoveredPages
	}
	return nil
}

func (x *Measurements) GetOrdinalGaps() []int64 {
	if x != nil {
		return x.OrdinalGaps
	}
	return nil
}

func (x *Measurements) GetScatteredSections() []string {
	if x != nil {
		return x.ScatteredSections
	}
	return nil
}

func (x *Measurements) GetMissingLocator() int64 {
	if x != nil {
		return x.MissingLocator
	}
	return 0
}

func (x *Measurements) GetChunksWithImages() int64 {
	if x != nil {
		return x.ChunksWithImages
	}
	return 0
}

// Finding is one graded defect, its evidence, and what it costs a caller.
type Finding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Severity      v1.Verdict             `protobuf:"varint,2,opt,name=severity,proto3,enum=docsearch.type.v1.Verdict" json:"severity,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Finding) Reset() {
	*x = Finding{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Finding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Finding) ProtoMessage() {}

func (x *Finding) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Finding.ProtoReflect.Descriptor instead.
func (*Finding) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{4}
}

func (x *Finding) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Finding) GetSeverity() v1.Verdict {
	if x != nil {
		return x.Severity
	}
	return v1.Verdict(0)
}

func (x *Finding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// VerifyReport is what verification found.
//
// Two questions, kept apart. Problems are integrity failures: the rows
// disagree with each other or with the document. Findings are quality
// defects, every one of them compatible with a clean ingest that reached
// 'ready'. A document can fail either while passing the other.
type VerifyReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Measurements  *Measurements          `protobuf:"bytes,2,opt,name=measurements,proto3" json:"measurements,omitempty"`
	Problems      []string               `protobuf:"bytes,3,rep,name=problems,proto3" json:"problems,omitempty"`
	Findings      []*Finding             `protobuf:"bytes,4,rep,name=findings,proto3" json:"findings,omitempty"`
	Verdict       v1.Verdict             `protobuf:"varint,5,opt,name=verdict,proto3,enum=docsearch.type.v1.Verdict" json:"verdict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyReport) Reset() {
	*x = VerifyReport{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyReport) ProtoMessage() {}

func (x *VerifyReport) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyReport.ProtoReflect.Descriptor instead.
func (*VerifyReport) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyReport) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *VerifyReport) GetMeasurements() *Measurements {
	if x != nil {
		return x.Measurements
	}
	return nil
}

func (x *VerifyReport) GetProblems() []string {
	if x != nil {
		return x.Problems
	}
	return nil
}

func (x *VerifyReport) GetFindings() []*Finding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *VerifyReport) GetVerdict() v1.Verdict {
	if x != nil {
		return x.Verdict
	}
	return v1.Verdict(0)
}

// InspectFinding is one question asked of a document before ingesting it.
type InspectFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         v1.Level               `protobuf:"varint,1,opt,name=level,proto3,enum=docsearch.type.v1.Level" json:"level,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectFinding) Reset() {
	*x = InspectFinding{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectFinding) ProtoMessage() {}

func (x *InspectFinding) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectFinding.ProtoReflect.Descriptor instead.
func (*InspectFinding) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{6}
}

func (x *InspectFinding) GetLevel() v1.Level {
	if x != nil {
		return x.Level
	}
	return v1.Level(0)
}

func (x *InspectFinding) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *InspectFinding) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// InspectReport is what reconnaissance made of a target, having written
// nothing.
type InspectReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A path for a file, a seed URL for a site.
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// The structure source ingest would end up using, and how much it can be
	// trusted.
	PredictedSource string            `protobuf:"bytes,3,opt,name=predicted_source,json=predictedSource,proto3" json:"predicted_source,omitempty"`
	PredictedTier   string            `protobuf:"bytes,4,opt,name=predicted_tier,json=predictedTier,proto3" json:"predicted_tier,omitempty"`
	PageCount       *int64            `protobuf:"varint,5,opt,name=page_count,json=pageCount,proto3,oneof" json:"page_count,omitempty"`
	Findings        []*InspectFinding `protobuf:"bytes,6,rep,name=findings,proto3" json:"findings,omitempty"`
	// Blocked is true where ingest would refuse the target, or should.
	Blocked       bool `protobuf:"varint,7,opt,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectReport) Reset() {
	*x = InspectReport{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectReport) ProtoMessage() {}

func (x *InspectReport) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectReport.ProtoReflect.Descriptor instead.
func (*InspectReport) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{7}
}

func (x *InspectReport) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *InspectReport) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *InspectReport) GetPredictedSource() string {
	if x != nil {
		return x.PredictedSource
	}
	return ""
}

func (x *InspectReport) GetPredictedTier() string {
	if x != nil {
		return x.PredictedTier
	}
	return ""
}

func (x *InspectReport) GetPageCount() int64 {
	if x != nil && x.PageCount != nil {
		return *x.PageCount
	}
	return 0
}

func (x *InspectReport) GetFindings() []*InspectFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *InspectReport) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{8}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *VerifyReport          `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyResponse) GetReport() *VerifyReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type InspectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A path inside the configured library root, or the URL of a site.
	Target        string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{12}
}

func (x *InspectRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type InspectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *InspectReport         `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{13}
}

func (x *InspectResponse) GetReport() *InspectReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_docsearch_document_v1_document_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docsearch_document_v1_document_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_docsearch_document_v1_document_proto_rawDescGZIP(), []int{15}
}

var File_docsearch_document_v1_document_proto protoreflect.FileDescriptor

const file_docsearch_document_v1_document_proto_rawDesc = "" +
	"\n" +
	"$docsearch/document/v1/document.proto\x12\x15docsearch.document.v1\x1a\x1edocsearch/type/v1/common.proto\"\xe2\x02\n" +
	"\bDocument\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12>\n" +
	"\vsource_kind\x18\x04 \x01(\x0e2\x1d.docsearch.type.v1.SourceKindR\n" +
	"sourceKind\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\"\n" +
	"\n" +
	"page_count\x18\x06 \x01(\x03H\x00R\tpageCount\x88\x01\x01\x12$\n" +
	"\vchunk_count\x18\a \x01(\x03H\x01R\n" +
	"chunkCount\x88\x01\x01\x124\n" +
	"\aquality\x18\b \x01(\x0e2\x1a.docsearch.type.v1.QualityR\aquality\x12\x1a\n" +
	"\bwarnings\x18\t \x03(\tR\bwarningsB\r\n" +
	"\v_page_countB\x0e\n" +
	"\f_chunk_count\"\x85\x01\n" +
	"\vTokenSpread\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x03R\x03min\x12\x16\n" +
	"\x06median\x18\x02 \x01(\x03R\x06median\x12\x10\n" +
	"\x03p95\x18\x03 \x01(\x03R\x03p95\x12\x10\n" +
	"\x03max\x18\x04 \x01(\x03R\x03max\x12\x12\n" +
	"\x04mean\x18\x05 \x01(\x03R\x04mean\x12\x14\n" +
	"\x05total\x18\x06 \x01(\x03R\x05total\"a\n" +
	"\n" +
	"SizedChunk\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\x03R\aordinal\x12\x16\n" +
	"\x06tokens\x18\x02 \x01(\x03R\x06tokens\x12!\n" +
	"\fheading_path\x18\x03 \x01(\tR\vheadingPath\"\xb9\x03\n" +
	"\fMeasurements\x12\x1f\n" +
	"\vchunk_count\x18\x01 \x01(\x03R\n" +
	"chunkCount\x12:\n" +
	"\x06tokens\x18\x02 \x01(\v2\".docsearch.document.v1.TokenSpreadR\x06tokens\x12;\n" +
	"\alongest\x18\x03 \x03(\v2!.docsearch.document.v1.SizedChunkR\alongest\x12=\n" +
	"\bshortest\x18\x04 \x03(\v2!.docsearch.document.v1.SizedChunkR\bshortest\x12'\n" +
	"\x0funcovered_pages\x18\x05 \x03(\x03R\x0euncoveredPages\x12!\n" +
	"\fordinal_gaps\x18\x06 \x03(\x03R\vordinalGaps\x12-\n" +
	"\x12scattered_sections\x18\a \x03(\tR\x11scatteredSections\x12'\n" +
	"\x0fmissing_locator\x18\b \x01(\x03R\x0emissingLocator\x12,\n" +
	"\x12chunks_with_images\x18\t \x01(\x03R\x10chunksWithImages\"m\n" +
	"\aFinding\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x126\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x1a.docsearch.type.v1.VerdictR\bseverity\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xa2\x02\n" +
	"\fVerifyReport\x12;\n" +
	"\bdocument\x18\x01 \x01(\v2\x1f.docsearch.document.v1.DocumentR\bdocument\x12G\n" +
	"\fmeasurements\x18\x02 \x01(\v2#.docsearch.document.v1.MeasurementsR\fmeasurements\x12\x1a\n" +
	"\bproblems\x18\x03 \x03(\tR\bproblems\x12:\n" +
	"\bfindings\x18\x04 \x03(\v2\x1e.docsearch.document.v1.FindingR\bfindings\x124\n" +
	"\averdict\x18\x05 \x01(\x0e2\x1a.docsearch.type.v1.VerdictR\averdict\"n\n" +
	"\x0eInspectFinding\x12.\n" +
	"\x05level\x18\x01 \x01(\x0e2\x18.docsearch.type.v1.LevelR\x05level\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\"\xa1\x02\n" +
	"\rInspectReport\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12)\n" +
	"\x10predicted_source\x18\x03 \x01(\tR\x0fpredictedSource\x12%\n" +
	"\x0epredicted_tier\x18\x04 \x01(\tR\rpredictedTier\x12\"\n" +
	"\n" +
	"page_count\x18\x05 \x01(\x03H\x00R\tpageCount\x88\x01\x01\x12A\n" +
	"\bfindings\x18\x06 \x03(\v2%.docsearch.document.v1.InspectFindingR\bfindings\x12\x18\n" +
	"\ablocked\x18\a \x01(\bR\ablockedB\r\n" +
	"\v_page_count\"\r\n" +
	"\vListRequest\"M\n" +
	"\fListResponse\x12=\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1f.docsearch.document.v1.DocumentR\tdocuments\"&\n" +
	"\rVerifyRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\"M\n" +
	"\x0eVerifyResponse\x12;\n" +
	"\x06report\x18\x01 \x01(\v2#.docsearch.document.v1.VerifyReportR\x06report\"(\n" +
	"\x0eInspectRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\"O\n" +
	"\x0fInspectResponse\x12<\n" +
	"\x06report\x18\x01 \x01(\v2$.docsearch.document.v1.InspectReportR\x06report\"&\n" +
	"\rRemoveRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\"\x10\n" +
	"\x0eRemoveResponse2\xf2\x02\n" +
	"\x0fDocumentService\x12Q\n" +
	"\x04List\x12\".docsearch.document.v1.ListRequest\x1a#.docsearch.document.v1.ListResponse\"\x00\x12W\n" +
	"\x06Verify\x12$.docsearch.document.v1.VerifyRequest\x1a%.docsearch.document.v1.VerifyResponse\"\x00\x12Z\n" +
	"\aInspect\x12%.docsearch.document.v1.InspectRequest\x1a&.docsearch.document.v1.InspectResponse\"\x00\x12W\n" +
	"\x06Remove\x12$.docsearch.document.v1.RemoveRequest\x1a%.docsearch.document.v1.RemoveResponse\"\x00B\xef\x01\n" +
	"\x19com.docsearch.document.v1B\rDocumentProtoP\x01ZMgithub.com/bamsammich/docsearch/internal/api/docsearch/document/v1;documentv1\xa2\x02\x03DDX\xaa\x02\x15Docsearch.Document.V1\xca\x02\x15Docsearch\\Document\\V1\xe2\x02!Docsearch\\Document\\V1\\GPBMetadata\xea\x02\x17Docsearch::Document::V1b\x06proto3"

var (
	file_docsearch_document_v1_document_proto_rawDescOnce sync.Once
	file_docsearch_document_v1_document_proto_rawDescData []byte
)

func file_docsearch_document_v1_document_proto_rawDescGZIP() []byte {
	file_docsearch_document_v1_document_proto_rawDescOnce.Do(func() {
		file_docsearch_document_v1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docsearch_document_v1_document_proto_rawDesc), len(file_docsearch_document_v1_document_proto_rawDesc)))
	})
	return file_docsearch_document_v1_document_proto_rawDescData
}

var file_docsearch_document_v1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_docsearch_document_v1_document_proto_goTypes = []any{
	(*Document)(nil),        // 0: docsearch.document.v1.Document
	(*TokenSpread)(nil),     // 1: docsearch.document.v1.TokenSpread
	(*SizedChunk)(nil),      // 2: docsearch.document.v1.SizedChunk
	(*Measurements)(nil),    // 3: docsearch.document.v1.Measurements
	(*Finding)(nil),         // 4: docsearch.document.v1.Finding
	(*VerifyReport)(nil),    // 5: docsearch.document.v1.VerifyReport
	(*InspectFinding)(nil),  // 6: docsearch.document.v1.InspectFinding
	(*InspectReport)(nil),   // 7: docsearch.document.v1.InspectReport
	(*ListRequest)(nil),     // 8: docsearch.document.v1.ListRequest
	(*ListResponse)(nil),    // 9: docsearch.document.v1.ListResponse
	(*VerifyRequest)(nil),   // 10: docsearch.document.v1.VerifyRequest
	(*VerifyResponse)(nil),  // 11: docsearch.document.v1.VerifyResponse
	(*InspectRequest)(nil),  // 12: docsearch.document.v1.InspectRequest
	(*InspectResponse)(nil), // 13: docsearch.document.v1.InspectResponse
	(*RemoveRequest)(nil),   // 14: docsearch.document.v1.RemoveRequest
	(*RemoveResponse)(nil),  // 15: docsearch.document.v1.RemoveResponse
	(v1.SourceKind)(0),      // 16: docsearch.type.v1.SourceKind
	(v1.Quality)(0),         // 17: docsearch.type.v1.Quality
	(v1.Verdict)(0),         // 18: docsearch.type.v1.Verdict
	(v1.Level)(0),           // 19: docsearch.type.v1.Level
}
var file_docsearch_document_v1_document_proto_depIdxs = []int32{
	16, // 0: docsearch.document.v1.Document.source_kind:type_name -> docsearch.type.v1.SourceKind
	17, // 1: docsearch.document.v1.Document.quality:type_name -> docsearch.type.v1.Quality
	1,  // 2: docsearch.document.v1.Measurements.tokens:type_name -> docsearch.document.v1.TokenSpread
	2,  // 3: docsearch.document.v1.Measurements.longest:type_name -> docsearch.document.v1.SizedChunk
	2,  // 4: docsearch.document.v1.Measurements.shortest:type_name -> docsearch.document.v1.SizedChunk
	18, // 5: docsearch.document.v1.Finding.severity:type_name -> docsearch.type.v1.Verdict
	0,  // 6: docsearch.document.v1.VerifyReport.document:type_name -> docsearch.document.v1.Document
	3,  // 7: docsearch.document.v1.VerifyReport.measurements:type_name -> docsearch.document.v1.Measurements
	4,  // 8: docsearch.document.v1.VerifyReport.findings:type_name -> docsearch.document.v1.Finding
	18, // 9: docsearch.document.v1.VerifyReport.verdict:type_name -> docsearch.type.v1.Verdict
	19, // 10: docsearch.document.v1.InspectFinding.level:type_name -> docsearch.type.v1.Level
	6,  // 11: docsearch.document.v1.InspectReport.findings:type_name -> docsearch.document.v1.InspectFinding
	0,  // 12: docsearch.document.v1.ListResponse.documents:type_name -> docsearch.document.v1.Document
	5,  // 13: docsearch.document.v1.VerifyResponse.report:type_name -> docsearch.document.v1.VerifyReport
	7,  // 14: docsearch.document.v1.InspectResponse.report:type_name -> docsearch.document.v1.InspectReport
	8,  // 15: docsearch.document.v1.DocumentService.List:input_type -> docsearch.document.v1.ListRequest
	10, // 16: docsearch.document.v1.DocumentService.Verify:input_type -> docsearch.document.v1.VerifyRequest
	12, // 17: docsearch.document.v1.DocumentService.Inspect:input_type -> docsearch.document.v1.InspectRequest
	14, // 18: docsearch.document.v1.DocumentService.Remove:input_type -> docsearch.document.v1.RemoveRequest
	9,  // 19: docsearch.document.v1.DocumentService.List:output_type -> docsearch.document.v1.ListResponse
	11, // 20: docsearch.document.v1.DocumentService.Verify:output_type -> docsearch.document.v1.VerifyResponse
	13, // 21: docsearch.document.v1.DocumentService.Inspect:output_type -> docsearch.document.v1.InspectResponse
	15, // 22: docsearch.document.v1.DocumentService.Remove:output_type -> docsearch.document.v1.RemoveResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_docsearch_document_v1_document_proto_init() }
func file_docsearch_document_v1_document_proto_init() {
	if File_docsearch_document_v1_document_proto != nil {
		return
	}
	file_docsearch_document_v1_document_proto_msgTypes[0].OneofWrappers = []any{}
	file_docsearch_document_v1_document_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docsearch_document_v1_document_proto_rawDesc), len(file_docsearch_document_v1_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docsearch_document_v1_document_proto_goTypes,
		DependencyIndexes: file_docsearch_document_v1_document_proto_depIdxs,
		MessageInfos:      file_docsearch_document_v1_document_proto_msgTypes,
	}.Build()
	File_docsearch_document_v1_document_proto = out.File
	file_docsearch_document_v1_document_proto_goTypes = nil
	file_docsearch_document_v1_document_proto_depIdxs = nil
}
