// Command schema-snapshot writes the schema a migrated index ends up with.
//
// Migrations are the source of truth, and a source of truth nobody can read:
// once there are several, the only way to know the current shape is to replay
// them in your head. The snapshot is what a reviewer reads instead. A pull
// request that changes the schema carries the change to the snapshot beside
// the migration that caused it, so the diff shows both the step and the
// destination.
//
// Nothing reads the snapshot at runtime. It is generated by `mise run
// generate`, and `mise run check` and CI fail when it does not match what the
// migrations produce.
package main

import (
	"cmp"
	"context"
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	_ "modernc.org/sqlite" // the driver an index is written with

	"github.com/bamsammich/docsearch/internal/schema"
)

// out is where the snapshot lives: beside the migrations that produce it.
const out = "internal/schema/schema.snapshot.sql"

// header says what the file is for, in the file, because a generated
// artifact is read by people who did not go looking for it.
const header = `-- The schema a fully migrated index holds, written by
-- ` + "`mise run generate`" + `.
--
-- Reference only. Nothing reads this file: the migrations in
-- internal/schema/migrations are what build an index, and this is what they
-- add up to. It exists so a review can see the whole shape at once, and so a
-- schema change shows up as a diff of the destination rather than only as a
-- diff of the step.
--
-- SQLite's own objects, the shadow tables behind the full-text index, and
-- the indexes SQLite creates for a UNIQUE or PRIMARY KEY are left out: none
-- of them is written here, and all of them are noise in a review.
`

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "fatal:", err)
		os.Exit(1)
	}
}

func run() error {
	dir, err := os.MkdirTemp("", "schema-snapshot")
	if err != nil {
		return fmt.Errorf("make a scratch directory: %w", err)
	}
	defer func() { _ = os.RemoveAll(dir) }()

	db, err := sql.Open("sqlite", filepath.Join(dir, "index.db"))
	if err != nil {
		return fmt.Errorf("open a scratch index: %w", err)
	}
	defer func() { _ = db.Close() }()

	if err := schema.Create(context.Background(), db); err != nil {
		return err
	}
	objects, err := read(db)
	if err != nil {
		return err
	}
	return os.WriteFile(out, []byte(render(objects)), 0o600)
}

// object is one thing the database holds.
type object struct {
	kind string
	name string
	ddl  string
}

// read collects every object worth showing a reviewer.
func read(db *sql.DB) ([]object, error) {
	rows, err := db.Query(
		`SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL`)
	if err != nil {
		return nil, fmt.Errorf("read the schema: %w", err)
	}
	defer func() { _ = rows.Close() }()

	var all []object
	var virtual []string
	for rows.Next() {
		var o object
		if err := rows.Scan(&o.kind, &o.name, &o.ddl); err != nil {
			return nil, fmt.Errorf("read an object: %w", err)
		}
		if strings.HasPrefix(strings.ToUpper(o.ddl), "CREATE VIRTUAL TABLE") {
			virtual = append(virtual, o.name)
		}
		all = append(all, o)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("read the schema: %w", err)
	}
	return keep(all, virtual), nil
}

// keep drops what a reviewer did not write and cannot change.
func keep(all []object, virtual []string) []object {
	var kept []object
	for _, o := range all {
		if strings.HasPrefix(o.name, "sqlite_") || shadowOf(o.name, virtual) {
			continue
		}
		kept = append(kept, o)
	}
	slices.SortFunc(kept, func(a, b object) int {
		if by := cmp.Compare(order(a.kind), order(b.kind)); by != 0 {
			return by
		}
		return cmp.Compare(a.name, b.name)
	})
	return kept
}

// shadowOf reports whether a table is one an FTS5 table keeps its data in.
// Those are created by the virtual table, not by a migration.
func shadowOf(name string, virtual []string) bool {
	for _, v := range virtual {
		if name != v && strings.HasPrefix(name, v+"_") {
			return true
		}
	}
	return false
}

// order groups the objects the way someone reading a schema wants them:
// tables first, then what is built on top.
func order(kind string) int {
	switch kind {
	case "table":
		return 0
	case "view":
		return 1
	case "index":
		return 2
	case "trigger":
		return 3
	default:
		return 4
	}
}

// plural names a group of objects, since "indexs" is not a word.
func plural(kind string) string {
	if kind == "index" {
		return "indexes"
	}
	return kind + "s"
}

// render writes the objects as SQL, each statement terminated.
func render(objects []object) string {
	var b strings.Builder
	b.WriteString(header)
	kind := ""
	for _, o := range objects {
		if o.kind != kind {
			kind = o.kind
			fmt.Fprintf(&b, "\n-- %s\n", plural(kind))
		}
		b.WriteString("\n")
		b.WriteString(strings.TrimSpace(o.ddl))
		b.WriteString(";\n")
	}
	return b.String()
}
