// Command schema-snapshot writes the schema a fully migrated database holds.
//
// Migrations are the source of truth, and a source of truth nobody can read:
// once there are several, the only way to know the current shape is to replay
// them in your head. The snapshot is what a reviewer reads instead. A pull
// request that changes the schema carries the change to the snapshot beside
// the migration that caused it, so the diff shows both the step and the
// destination.
//
// Postgres describes its own shape through pg_dump, run inside the same
// container the tests use. A renderer of our own reading the catalog would
// be a second implementation of something the image already carries, and it
// would be the one with the bugs.
//
// Docker has to be running, as it does for the tests. Nothing reads the
// snapshot at runtime: it is generated by `mise run generate`, and `mise run
// check` and CI fail when it does not match what the migrations produce.
package main

import (
	"context"
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/bamsammich/docsearch/internal/pgtest"
	"github.com/bamsammich/docsearch/internal/schema"
)

// out is where the snapshot lives: beside the migrations that produce it.
const out = "internal/schema/schema.snapshot.sql"

// header says what the file is for, in the file, because a generated
// artifact is read by people who did not go looking for it.
const header = `-- The schema a fully migrated database holds, written by
-- ` + "`mise run generate`" + ` as pg_dump renders it.
--
-- Reference only. Nothing reads this file: the migrations in
-- internal/schema/migrations are what build a database, and this is what
-- they add up to. It exists so a review can see the whole shape at once, and
-- so a schema change shows up as a diff of the destination rather than only
-- as a diff of the step.
`

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "fatal:", err)
		os.Exit(1)
	}
}

func run() error {
	ctx := context.Background()
	report := &reporter{}
	pg := pgtest.Start(report)
	defer report.cleanUp()
	if report.failed != nil {
		return report.failed
	}

	if err := schema.Create(ctx, pg.Owner); err != nil {
		return err
	}
	// public only: the image ships TimescaleDB, whose own schemas would
	// otherwise fill the snapshot with objects docsearch never created.
	dumped, err := pg.Run(ctx,
		"pg_dump", "--schema-only", "--schema=public", "--no-owner",
		"--no-privileges", "--username", pgtest.OwnerRole, "docsearch")
	if err != nil {
		return err
	}
	return os.WriteFile(out, []byte(header+clean(dumped)), 0o600)
}

// settings is pg_dump's preamble of session GUCs, which says nothing about
// the schema and changes with the server's build.
var settings = regexp.MustCompile(`(?m)^SET [a-z_]+ = .*;\n`)

// clean drops what pg_dump writes for a restore rather than for a reader.
//
// The restrict tokens matter most: pg_dump writes a fresh random one on
// every run, so a snapshot keeping them would differ from itself and the
// generated-is-current check would fail on a tree nobody touched.
func clean(dumped string) string {
	dumped = settings.ReplaceAllString(dumped, "")
	dumped = strings.ReplaceAll(dumped,
		"SELECT pg_catalog.set_config('search_path', '', false);\n", "")
	var kept []string
	for line := range strings.Lines(dumped) {
		switch {
		case strings.HasPrefix(line, `\restrict `), strings.HasPrefix(line, `\unrestrict `):
			continue
		// The version banner would make every dump differ the day the image
		// moves.
		case strings.HasPrefix(line, "-- Dumped"):
			continue
		}
		kept = append(kept, line)
	}
	return strings.TrimLeft(strings.Join(kept, ""), "\n")
}

// reporter adapts this command to the harness, which was written for tests.
//
// Start takes what it needs from *testing.T: somewhere to put a failure, and
// somewhere to register the container's shutdown. A command has both, spelled
// differently.
type reporter struct {
	failed   error
	cleanups []func()
}

func (*reporter) Helper() {}

func (*reporter) Context() context.Context { return context.Background() }

func (r *reporter) Cleanup(fn func()) { r.cleanups = append(r.cleanups, fn) }

func (r *reporter) cleanUp() {
	for i := len(r.cleanups) - 1; i >= 0; i-- {
		r.cleanups[i]()
	}
}

func (r *reporter) Errorf(format string, args ...any) {
	if r.failed == nil {
		r.failed = fmt.Errorf(format, args...)
	}
}

// Fatalf records the failure and unwinds, since the harness expects a call
// that does not return and run() checks for one straight after Start.
func (r *reporter) Fatalf(format string, args ...any) {
	r.Errorf(format, args...)
	panic(r.failed)
}

func (*reporter) Logf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
}
