// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bamsammich/docsearch/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExtractor creates a new instance of MockExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtractor {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockExtractor is an autogenerated mock type for the Extractor type
type MockExtractor struct {
	mock.Mock
}

type MockExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtractor) EXPECT() *MockExtractor_Expecter {
	return &MockExtractor_Expecter{mock: &_m.Mock}
}

// Extract provides a mock function for the type MockExtractor
func (_mock *MockExtractor) Extract(ctx context.Context, path string) (*domain.Extraction, error) {
	ret := _mock.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 *domain.Extraction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Extraction, error)); ok {
		return returnFunc(ctx, path)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Extraction); ok {
		r0 = returnFunc(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Extraction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExtractor_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockExtractor_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *MockExtractor_Expecter) Extract(ctx any, path any) *MockExtractor_Extract_Call {
	return &MockExtractor_Extract_Call{Call: _e.mock.On("Extract", ctx, path)}
}

func (_c *MockExtractor_Extract_Call) Run(run func(ctx context.Context, path string)) *MockExtractor_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockExtractor_Extract_Call) Return(extraction *domain.Extraction, err error) *MockExtractor_Extract_Call {
	_c.Call.Return(extraction, err)
	return _c
}

func (_c *MockExtractor_Extract_Call) RunAndReturn(run func(ctx context.Context, path string) (*domain.Extraction, error)) *MockExtractor_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// Supports provides a mock function for the type MockExtractor
func (_mock *MockExtractor) Supports(path string) bool {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Supports")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockExtractor_Supports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Supports'
type MockExtractor_Supports_Call struct {
	*mock.Call
}

// Supports is a helper method to define mock.On call
//   - path string
func (_e *MockExtractor_Expecter) Supports(path any) *MockExtractor_Supports_Call {
	return &MockExtractor_Supports_Call{Call: _e.mock.On("Supports", path)}
}

func (_c *MockExtractor_Supports_Call) Run(run func(path string)) *MockExtractor_Supports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockExtractor_Supports_Call) Return(b bool) *MockExtractor_Supports_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockExtractor_Supports_Call) RunAndReturn(run func(path string) bool) *MockExtractor_Supports_Call {
	_c.Call.Return(run)
	return _c
}
