// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bamsammich/docsearch/internal/domain"
	"github.com/bamsammich/docsearch/internal/service/ingest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddChunks provides a mock function for the type MockRepository
func (_mock *MockRepository) AddChunks(ctx context.Context, docID string, chunks []domain.Chunk) error {
	ret := _mock.Called(ctx, docID, chunks)

	if len(ret) == 0 {
		panic("no return value specified for AddChunks")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []domain.Chunk) error); ok {
		r0 = returnFunc(ctx, docID, chunks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddChunks'
type MockRepository_AddChunks_Call struct {
	*mock.Call
}

// AddChunks is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
//   - chunks []domain.Chunk
func (_e *MockRepository_Expecter) AddChunks(ctx any, docID any, chunks any) *MockRepository_AddChunks_Call {
	return &MockRepository_AddChunks_Call{Call: _e.mock.On("AddChunks", ctx, docID, chunks)}
}

func (_c *MockRepository_AddChunks_Call) Run(run func(ctx context.Context, docID string, chunks []domain.Chunk)) *MockRepository_AddChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []domain.Chunk
		if args[2] != nil {
			arg2 = args[2].([]domain.Chunk)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_AddChunks_Call) Return(err error) *MockRepository_AddChunks_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddChunks_Call) RunAndReturn(run func(ctx context.Context, docID string, chunks []domain.Chunk) error) *MockRepository_AddChunks_Call {
	_c.Call.Return(run)
	return _c
}

// AddPagesAndTerms provides a mock function for the type MockRepository
func (_mock *MockRepository) AddPagesAndTerms(ctx context.Context, docID string, pages map[int]string, terms [][2]string) error {
	ret := _mock.Called(ctx, docID, pages, terms)

	if len(ret) == 0 {
		panic("no return value specified for AddPagesAndTerms")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[int]string, [][2]string) error); ok {
		r0 = returnFunc(ctx, docID, pages, terms)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_AddPagesAndTerms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPagesAndTerms'
type MockRepository_AddPagesAndTerms_Call struct {
	*mock.Call
}

// AddPagesAndTerms is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
//   - pages map[int]string
//   - terms [][2]string
func (_e *MockRepository_Expecter) AddPagesAndTerms(ctx any, docID any, pages any, terms any) *MockRepository_AddPagesAndTerms_Call {
	return &MockRepository_AddPagesAndTerms_Call{Call: _e.mock.On("AddPagesAndTerms", ctx, docID, pages, terms)}
}

func (_c *MockRepository_AddPagesAndTerms_Call) Run(run func(ctx context.Context, docID string, pages map[int]string, terms [][2]string)) *MockRepository_AddPagesAndTerms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[int]string
		if args[2] != nil {
			arg2 = args[2].(map[int]string)
		}
		var arg3 [][2]string
		if args[3] != nil {
			arg3 = args[3].([][2]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_AddPagesAndTerms_Call) Return(err error) *MockRepository_AddPagesAndTerms_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_AddPagesAndTerms_Call) RunAndReturn(run func(ctx context.Context, docID string, pages map[int]string, terms [][2]string) error) *MockRepository_AddPagesAndTerms_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(ctx context.Context, doc ingest.Document, replacing string) error {
	ret := _mock.Called(ctx, doc, replacing)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.Document, string) error); ok {
		r0 = returnFunc(ctx, doc, replacing)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - doc ingest.Document
//   - replacing string
func (_e *MockRepository_Expecter) Create(ctx any, doc any, replacing any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, doc, replacing)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, doc ingest.Document, replacing string)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ingest.Document
		if args[1] != nil {
			arg1 = args[1].(ingest.Document)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, doc ingest.Document, replacing string) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, docID string) error {
	ret := _mock.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, docID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
func (_e *MockRepository_Expecter) Delete(ctx any, docID any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, docID)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, docID string)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, docID string) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DocIDForIdentity provides a mock function for the type MockRepository
func (_mock *MockRepository) DocIDForIdentity(ctx context.Context, identity string) (string, error) {
	ret := _mock.Called(ctx, identity)

	if len(ret) == 0 {
		panic("no return value specified for DocIDForIdentity")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, identity)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, identity)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, identity)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_DocIDForIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DocIDForIdentity'
type MockRepository_DocIDForIdentity_Call struct {
	*mock.Call
}

// DocIDForIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - identity string
func (_e *MockRepository_Expecter) DocIDForIdentity(ctx any, identity any) *MockRepository_DocIDForIdentity_Call {
	return &MockRepository_DocIDForIdentity_Call{Call: _e.mock.On("DocIDForIdentity", ctx, identity)}
}

func (_c *MockRepository_DocIDForIdentity_Call) Run(run func(ctx context.Context, identity string)) *MockRepository_DocIDForIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DocIDForIdentity_Call) Return(s string, err error) *MockRepository_DocIDForIdentity_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepository_DocIDForIdentity_Call) RunAndReturn(run func(ctx context.Context, identity string) (string, error)) *MockRepository_DocIDForIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// DocIDsWithPrefix provides a mock function for the type MockRepository
func (_mock *MockRepository) DocIDsWithPrefix(ctx context.Context, prefix string) ([]string, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for DocIDsWithPrefix")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_DocIDsWithPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DocIDsWithPrefix'
type MockRepository_DocIDsWithPrefix_Call struct {
	*mock.Call
}

// DocIDsWithPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockRepository_Expecter) DocIDsWithPrefix(ctx any, prefix any) *MockRepository_DocIDsWithPrefix_Call {
	return &MockRepository_DocIDsWithPrefix_Call{Call: _e.mock.On("DocIDsWithPrefix", ctx, prefix)}
}

func (_c *MockRepository_DocIDsWithPrefix_Call) Run(run func(ctx context.Context, prefix string)) *MockRepository_DocIDsWithPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DocIDsWithPrefix_Call) Return(strings []string, err error) *MockRepository_DocIDsWithPrefix_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRepository_DocIDsWithPrefix_Call) RunAndReturn(run func(ctx context.Context, prefix string) ([]string, error)) *MockRepository_DocIDsWithPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReady provides a mock function for the type MockRepository
func (_mock *MockRepository) MarkReady(ctx context.Context, ready ingest.Ready) error {
	ret := _mock.Called(ctx, ready)

	if len(ret) == 0 {
		panic("no return value specified for MarkReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.Ready) error); ok {
		r0 = returnFunc(ctx, ready)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_MarkReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReady'
type MockRepository_MarkReady_Call struct {
	*mock.Call
}

// MarkReady is a helper method to define mock.On call
//   - ctx context.Context
//   - ready ingest.Ready
func (_e *MockRepository_Expecter) MarkReady(ctx any, ready any) *MockRepository_MarkReady_Call {
	return &MockRepository_MarkReady_Call{Call: _e.mock.On("MarkReady", ctx, ready)}
}

func (_c *MockRepository_MarkReady_Call) Run(run func(ctx context.Context, ready ingest.Ready)) *MockRepository_MarkReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ingest.Ready
		if args[1] != nil {
			arg1 = args[1].(ingest.Ready)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_MarkReady_Call) Return(err error) *MockRepository_MarkReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_MarkReady_Call) RunAndReturn(run func(ctx context.Context, ready ingest.Ready) error) *MockRepository_MarkReady_Call {
	_c.Call.Return(run)
	return _c
}

// ReadyWithDigest provides a mock function for the type MockRepository
func (_mock *MockRepository) ReadyWithDigest(ctx context.Context, digest string) (*ingest.Existing, error) {
	ret := _mock.Called(ctx, digest)

	if len(ret) == 0 {
		panic("no return value specified for ReadyWithDigest")
	}

	var r0 *ingest.Existing
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ingest.Existing, error)); ok {
		return returnFunc(ctx, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ingest.Existing); ok {
		r0 = returnFunc(ctx, digest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ingest.Existing)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ReadyWithDigest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadyWithDigest'
type MockRepository_ReadyWithDigest_Call struct {
	*mock.Call
}

// ReadyWithDigest is a helper method to define mock.On call
//   - ctx context.Context
//   - digest string
func (_e *MockRepository_Expecter) ReadyWithDigest(ctx any, digest any) *MockRepository_ReadyWithDigest_Call {
	return &MockRepository_ReadyWithDigest_Call{Call: _e.mock.On("ReadyWithDigest", ctx, digest)}
}

func (_c *MockRepository_ReadyWithDigest_Call) Run(run func(ctx context.Context, digest string)) *MockRepository_ReadyWithDigest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ReadyWithDigest_Call) Return(existing *ingest.Existing, err error) *MockRepository_ReadyWithDigest_Call {
	_c.Call.Return(existing, err)
	return _c
}

func (_c *MockRepository_ReadyWithDigest_Call) RunAndReturn(run func(ctx context.Context, digest string) (*ingest.Existing, error)) *MockRepository_ReadyWithDigest_Call {
	_c.Call.Return(run)
	return _c
}
