// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bamsammich/docsearch/internal/domain"
	"github.com/bamsammich/docsearch/internal/service/ingest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function for the type MockSource
func (_mock *MockSource) Acquire(ctx context.Context, progress ingest.Progress) error {
	ret := _mock.Called(ctx, progress)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.Progress) error); ok {
		r0 = returnFunc(ctx, progress)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSource_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type MockSource_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
//   - progress ingest.Progress
func (_e *MockSource_Expecter) Acquire(ctx any, progress any) *MockSource_Acquire_Call {
	return &MockSource_Acquire_Call{Call: _e.mock.On("Acquire", ctx, progress)}
}

func (_c *MockSource_Acquire_Call) Run(run func(ctx context.Context, progress ingest.Progress)) *MockSource_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ingest.Progress
		if args[1] != nil {
			arg1 = args[1].(ingest.Progress)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Acquire_Call) Return(err error) *MockSource_Acquire_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSource_Acquire_Call) RunAndReturn(run func(ctx context.Context, progress ingest.Progress) error) *MockSource_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Digest provides a mock function for the type MockSource
func (_mock *MockSource) Digest() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Digest")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSource_Digest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Digest'
type MockSource_Digest_Call struct {
	*mock.Call
}

// Digest is a helper method to define mock.On call
func (_e *MockSource_Expecter) Digest() *MockSource_Digest_Call {
	return &MockSource_Digest_Call{Call: _e.mock.On("Digest")}
}

func (_c *MockSource_Digest_Call) Run(run func()) *MockSource_Digest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Digest_Call) Return(s string) *MockSource_Digest_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSource_Digest_Call) RunAndReturn(run func() string) *MockSource_Digest_Call {
	_c.Call.Return(run)
	return _c
}

// Extract provides a mock function for the type MockSource
func (_mock *MockSource) Extract(ctx context.Context, progress ingest.Progress) (*domain.Extraction, error) {
	ret := _mock.Called(ctx, progress)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 *domain.Extraction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.Progress) (*domain.Extraction, error)); ok {
		return returnFunc(ctx, progress)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.Progress) *domain.Extraction); ok {
		r0 = returnFunc(ctx, progress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Extraction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ingest.Progress) error); ok {
		r1 = returnFunc(ctx, progress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockSource_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - progress ingest.Progress
func (_e *MockSource_Expecter) Extract(ctx any, progress any) *MockSource_Extract_Call {
	return &MockSource_Extract_Call{Call: _e.mock.On("Extract", ctx, progress)}
}

func (_c *MockSource_Extract_Call) Run(run func(ctx context.Context, progress ingest.Progress)) *MockSource_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ingest.Progress
		if args[1] != nil {
			arg1 = args[1].(ingest.Progress)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Extract_Call) Return(extraction *domain.Extraction, err error) *MockSource_Extract_Call {
	_c.Call.Return(extraction, err)
	return _c
}

func (_c *MockSource_Extract_Call) RunAndReturn(run func(ctx context.Context, progress ingest.Progress) (*domain.Extraction, error)) *MockSource_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// Identity provides a mock function for the type MockSource
func (_mock *MockSource) Identity() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Identity")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSource_Identity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Identity'
type MockSource_Identity_Call struct {
	*mock.Call
}

// Identity is a helper method to define mock.On call
func (_e *MockSource_Expecter) Identity() *MockSource_Identity_Call {
	return &MockSource_Identity_Call{Call: _e.mock.On("Identity")}
}

func (_c *MockSource_Identity_Call) Run(run func()) *MockSource_Identity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Identity_Call) Return(s string) *MockSource_Identity_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSource_Identity_Call) RunAndReturn(run func() string) *MockSource_Identity_Call {
	_c.Call.Return(run)
	return _c
}

// Kind provides a mock function for the type MockSource
func (_mock *MockSource) Kind() domain.SourceKind {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kind")
	}

	var r0 domain.SourceKind
	if returnFunc, ok := ret.Get(0).(func() domain.SourceKind); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(domain.SourceKind)
	}
	return r0
}

// MockSource_Kind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kind'
type MockSource_Kind_Call struct {
	*mock.Call
}

// Kind is a helper method to define mock.On call
func (_e *MockSource_Expecter) Kind() *MockSource_Kind_Call {
	return &MockSource_Kind_Call{Call: _e.mock.On("Kind")}
}

func (_c *MockSource_Kind_Call) Run(run func()) *MockSource_Kind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_Kind_Call) Return(sourceKind domain.SourceKind) *MockSource_Kind_Call {
	_c.Call.Return(sourceKind)
	return _c
}

func (_c *MockSource_Kind_Call) RunAndReturn(run func() domain.SourceKind) *MockSource_Kind_Call {
	_c.Call.Return(run)
	return _c
}
