// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bamsammich/docsearch/internal/service/ingest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIngester creates a new instance of MockIngester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIngester(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIngester {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockIngester{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockIngester is an autogenerated mock type for the Ingester type
type MockIngester struct {
	mock.Mock
}

type MockIngester_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIngester) EXPECT() *MockIngester_Expecter {
	return &MockIngester_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockIngester
func (_mock *MockIngester) Run(ctx context.Context, src ingest.Source, opts ingest.Options) (*ingest.Result, error) {
	ret := _mock.Called(ctx, src, opts)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *ingest.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.Source, ingest.Options) (*ingest.Result, error)); ok {
		return returnFunc(ctx, src, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ingest.Source, ingest.Options) *ingest.Result); ok {
		r0 = returnFunc(ctx, src, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ingest.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ingest.Source, ingest.Options) error); ok {
		r1 = returnFunc(ctx, src, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIngester_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockIngester_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - src ingest.Source
//   - opts ingest.Options
func (_e *MockIngester_Expecter) Run(ctx any, src any, opts any) *MockIngester_Run_Call {
	return &MockIngester_Run_Call{Call: _e.mock.On("Run", ctx, src, opts)}
}

func (_c *MockIngester_Run_Call) Run(run func(ctx context.Context, src ingest.Source, opts ingest.Options)) *MockIngester_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ingest.Source
		if args[1] != nil {
			arg1 = args[1].(ingest.Source)
		}
		var arg2 ingest.Options
		if args[2] != nil {
			arg2 = args[2].(ingest.Options)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIngester_Run_Call) Return(result *ingest.Result, err error) *MockIngester_Run_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockIngester_Run_Call) RunAndReturn(run func(ctx context.Context, src ingest.Source, opts ingest.Options) (*ingest.Result, error)) *MockIngester_Run_Call {
	_c.Call.Return(run)
	return _c
}
