// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/bamsammich/docsearch/internal/service/worker"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobs creates a new instance of MockJobs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobs(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobs {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockJobs{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockJobs is an autogenerated mock type for the Jobs type
type MockJobs struct {
	mock.Mock
}

type MockJobs_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobs) EXPECT() *MockJobs_Expecter {
	return &MockJobs_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockJobs
func (_mock *MockJobs) Cancel(ctx context.Context, id int64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobs_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockJobs_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockJobs_Expecter) Cancel(ctx any, id any) *MockJobs_Cancel_Call {
	return &MockJobs_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id)}
}

func (_c *MockJobs_Cancel_Call) Run(run func(ctx context.Context, id int64)) *MockJobs_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobs_Cancel_Call) Return(err error) *MockJobs_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobs_Cancel_Call) RunAndReturn(run func(ctx context.Context, id int64) error) *MockJobs_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// CancelRequested provides a mock function for the type MockJobs
func (_mock *MockJobs) CancelRequested(ctx context.Context, id int64) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CancelRequested")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobs_CancelRequested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelRequested'
type MockJobs_CancelRequested_Call struct {
	*mock.Call
}

// CancelRequested is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockJobs_Expecter) CancelRequested(ctx any, id any) *MockJobs_CancelRequested_Call {
	return &MockJobs_CancelRequested_Call{Call: _e.mock.On("CancelRequested", ctx, id)}
}

func (_c *MockJobs_CancelRequested_Call) Run(run func(ctx context.Context, id int64)) *MockJobs_CancelRequested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobs_CancelRequested_Call) Return(b bool, err error) *MockJobs_CancelRequested_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockJobs_CancelRequested_Call) RunAndReturn(run func(ctx context.Context, id int64) (bool, error)) *MockJobs_CancelRequested_Call {
	_c.Call.Return(run)
	return _c
}

// Claim provides a mock function for the type MockJobs
func (_mock *MockJobs) Claim(ctx context.Context, lease time.Duration, maxAttempts int) (*worker.Job, error) {
	ret := _mock.Called(ctx, lease, maxAttempts)

	if len(ret) == 0 {
		panic("no return value specified for Claim")
	}

	var r0 *worker.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) (*worker.Job, error)); ok {
		return returnFunc(ctx, lease, maxAttempts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration, int) *worker.Job); ok {
		r0 = returnFunc(ctx, lease, maxAttempts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*worker.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration, int) error); ok {
		r1 = returnFunc(ctx, lease, maxAttempts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobs_Claim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Claim'
type MockJobs_Claim_Call struct {
	*mock.Call
}

// Claim is a helper method to define mock.On call
//   - ctx context.Context
//   - lease time.Duration
//   - maxAttempts int
func (_e *MockJobs_Expecter) Claim(ctx any, lease any, maxAttempts any) *MockJobs_Claim_Call {
	return &MockJobs_Claim_Call{Call: _e.mock.On("Claim", ctx, lease, maxAttempts)}
}

func (_c *MockJobs_Claim_Call) Run(run func(ctx context.Context, lease time.Duration, maxAttempts int)) *MockJobs_Claim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobs_Claim_Call) Return(job *worker.Job, err error) *MockJobs_Claim_Call {
	_c.Call.Return(job, err)
	return _c
}

func (_c *MockJobs_Claim_Call) RunAndReturn(run func(ctx context.Context, lease time.Duration, maxAttempts int) (*worker.Job, error)) *MockJobs_Claim_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteWithoutDocument provides a mock function for the type MockJobs
func (_mock *MockJobs) CompleteWithoutDocument(ctx context.Context, id int64, docID string) error {
	ret := _mock.Called(ctx, id, docID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteWithoutDocument")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, docID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobs_CompleteWithoutDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteWithoutDocument'
type MockJobs_CompleteWithoutDocument_Call struct {
	*mock.Call
}

// CompleteWithoutDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - docID string
func (_e *MockJobs_Expecter) CompleteWithoutDocument(ctx any, id any, docID any) *MockJobs_CompleteWithoutDocument_Call {
	return &MockJobs_CompleteWithoutDocument_Call{Call: _e.mock.On("CompleteWithoutDocument", ctx, id, docID)}
}

func (_c *MockJobs_CompleteWithoutDocument_Call) Run(run func(ctx context.Context, id int64, docID string)) *MockJobs_CompleteWithoutDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobs_CompleteWithoutDocument_Call) Return(err error) *MockJobs_CompleteWithoutDocument_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobs_CompleteWithoutDocument_Call) RunAndReturn(run func(ctx context.Context, id int64, docID string) error) *MockJobs_CompleteWithoutDocument_Call {
	_c.Call.Return(run)
	return _c
}

// Finish provides a mock function for the type MockJobs
func (_mock *MockJobs) Finish(ctx context.Context, id int64, outcome worker.Outcome, reason string, permanent bool) error {
	ret := _mock.Called(ctx, id, outcome, reason, permanent)

	if len(ret) == 0 {
		panic("no return value specified for Finish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, worker.Outcome, string, bool) error); ok {
		r0 = returnFunc(ctx, id, outcome, reason, permanent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobs_Finish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Finish'
type MockJobs_Finish_Call struct {
	*mock.Call
}

// Finish is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - outcome worker.Outcome
//   - reason string
//   - permanent bool
func (_e *MockJobs_Expecter) Finish(ctx any, id any, outcome any, reason any, permanent any) *MockJobs_Finish_Call {
	return &MockJobs_Finish_Call{Call: _e.mock.On("Finish", ctx, id, outcome, reason, permanent)}
}

func (_c *MockJobs_Finish_Call) Run(run func(ctx context.Context, id int64, outcome worker.Outcome, reason string, permanent bool)) *MockJobs_Finish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 worker.Outcome
		if args[2] != nil {
			arg2 = args[2].(worker.Outcome)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockJobs_Finish_Call) Return(err error) *MockJobs_Finish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobs_Finish_Call) RunAndReturn(run func(ctx context.Context, id int64, outcome worker.Outcome, reason string, permanent bool) error) *MockJobs_Finish_Call {
	_c.Call.Return(run)
	return _c
}

// RecordDocID provides a mock function for the type MockJobs
func (_mock *MockJobs) RecordDocID(ctx context.Context, id int64, docID string) error {
	ret := _mock.Called(ctx, id, docID)

	if len(ret) == 0 {
		panic("no return value specified for RecordDocID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = returnFunc(ctx, id, docID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobs_RecordDocID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordDocID'
type MockJobs_RecordDocID_Call struct {
	*mock.Call
}

// RecordDocID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - docID string
func (_e *MockJobs_Expecter) RecordDocID(ctx any, id any, docID any) *MockJobs_RecordDocID_Call {
	return &MockJobs_RecordDocID_Call{Call: _e.mock.On("RecordDocID", ctx, id, docID)}
}

func (_c *MockJobs_RecordDocID_Call) Run(run func(ctx context.Context, id int64, docID string)) *MockJobs_RecordDocID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobs_RecordDocID_Call) Return(err error) *MockJobs_RecordDocID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobs_RecordDocID_Call) RunAndReturn(run func(ctx context.Context, id int64, docID string) error) *MockJobs_RecordDocID_Call {
	_c.Call.Return(run)
	return _c
}

// RecordProgress provides a mock function for the type MockJobs
func (_mock *MockJobs) RecordProgress(ctx context.Context, id int64, phase string, cur int, tot int, lease time.Duration) error {
	ret := _mock.Called(ctx, id, phase, cur, tot, lease)

	if len(ret) == 0 {
		panic("no return value specified for RecordProgress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, string, int, int, time.Duration) error); ok {
		r0 = returnFunc(ctx, id, phase, cur, tot, lease)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobs_RecordProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordProgress'
type MockJobs_RecordProgress_Call struct {
	*mock.Call
}

// RecordProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
//   - phase string
//   - cur int
//   - tot int
//   - lease time.Duration
func (_e *MockJobs_Expecter) RecordProgress(ctx any, id any, phase any, cur any, tot any, lease any) *MockJobs_RecordProgress_Call {
	return &MockJobs_RecordProgress_Call{Call: _e.mock.On("RecordProgress", ctx, id, phase, cur, tot, lease)}
}

func (_c *MockJobs_RecordProgress_Call) Run(run func(ctx context.Context, id int64, phase string, cur int, tot int, lease time.Duration)) *MockJobs_RecordProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		var arg5 time.Duration
		if args[5] != nil {
			arg5 = args[5].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockJobs_RecordProgress_Call) Return(err error) *MockJobs_RecordProgress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobs_RecordProgress_Call) RunAndReturn(run func(ctx context.Context, id int64, phase string, cur int, tot int, lease time.Duration) error) *MockJobs_RecordProgress_Call {
	_c.Call.Return(run)
	return _c
}
