// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bamsammich/docsearch/internal/service/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockQueue
func (_mock *MockQueue) Add(ctx context.Context, source string, title string) (int64, int, error) {
	ret := _mock.Called(ctx, source, title)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 int64
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (int64, int, error)); ok {
		return returnFunc(ctx, source, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) int64); ok {
		r0 = returnFunc(ctx, source, title)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) int); ok {
		r1 = returnFunc(ctx, source, title)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, source, title)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQueue_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockQueue_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - source string
//   - title string
func (_e *MockQueue_Expecter) Add(ctx any, source any, title any) *MockQueue_Add_Call {
	return &MockQueue_Add_Call{Call: _e.mock.On("Add", ctx, source, title)}
}

func (_c *MockQueue_Add_Call) Run(run func(ctx context.Context, source string, title string)) *MockQueue_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueue_Add_Call) Return(id int64, position int, err error) *MockQueue_Add_Call {
	_c.Call.Return(id, position, err)
	return _c
}

func (_c *MockQueue_Add_Call) RunAndReturn(run func(ctx context.Context, source string, title string) (int64, int, error)) *MockQueue_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockQueue
func (_mock *MockQueue) List(ctx context.Context, includeCompleted bool, limit int) ([]job.Job, error) {
	ret := _mock.Called(ctx, includeCompleted, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []job.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, int) ([]job.Job, error)); ok {
		return returnFunc(ctx, includeCompleted, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, int) []job.Job); ok {
		r0 = returnFunc(ctx, includeCompleted, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]job.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, int) error); ok {
		r1 = returnFunc(ctx, includeCompleted, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockQueue_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - includeCompleted bool
//   - limit int
func (_e *MockQueue_Expecter) List(ctx any, includeCompleted any, limit any) *MockQueue_List_Call {
	return &MockQueue_List_Call{Call: _e.mock.On("List", ctx, includeCompleted, limit)}
}

func (_c *MockQueue_List_Call) Run(run func(ctx context.Context, includeCompleted bool, limit int)) *MockQueue_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueue_List_Call) Return(jobs []job.Job, err error) *MockQueue_List_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockQueue_List_Call) RunAndReturn(run func(ctx context.Context, includeCompleted bool, limit int) ([]job.Job, error)) *MockQueue_List_Call {
	_c.Call.Return(run)
	return _c
}

// RequestCancel provides a mock function for the type MockQueue
func (_mock *MockQueue) RequestCancel(ctx context.Context, id int64) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RequestCancel")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_RequestCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestCancel'
type MockQueue_RequestCancel_Call struct {
	*mock.Call
}

// RequestCancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockQueue_Expecter) RequestCancel(ctx any, id any) *MockQueue_RequestCancel_Call {
	return &MockQueue_RequestCancel_Call{Call: _e.mock.On("RequestCancel", ctx, id)}
}

func (_c *MockQueue_RequestCancel_Call) Run(run func(ctx context.Context, id int64)) *MockQueue_RequestCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_RequestCancel_Call) Return(status string, err error) *MockQueue_RequestCancel_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockQueue_RequestCancel_Call) RunAndReturn(run func(ctx context.Context, id int64) (string, error)) *MockQueue_RequestCancel_Call {
	_c.Call.Return(run)
	return _c
}
