// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTargets creates a new instance of MockTargets. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTargets(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTargets {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockTargets{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockTargets is an autogenerated mock type for the Targets type
type MockTargets struct {
	mock.Mock
}

type MockTargets_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTargets) EXPECT() *MockTargets_Expecter {
	return &MockTargets_Expecter{mock: &_m.Mock}
}

// Targets provides a mock function for the type MockTargets
func (_mock *MockTargets) Targets(target string) ([]string, error) {
	ret := _mock.Called(target)

	if len(ret) == 0 {
		panic("no return value specified for Targets")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(target)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTargets_Targets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Targets'
type MockTargets_Targets_Call struct {
	*mock.Call
}

// Targets is a helper method to define mock.On call
//   - target string
func (_e *MockTargets_Expecter) Targets(target any) *MockTargets_Targets_Call {
	return &MockTargets_Targets_Call{Call: _e.mock.On("Targets", target)}
}

func (_c *MockTargets_Targets_Call) Run(run func(target string)) *MockTargets_Targets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTargets_Targets_Call) Return(strings []string, err error) *MockTargets_Targets_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockTargets_Targets_Call) RunAndReturn(run func(target string) ([]string, error)) *MockTargets_Targets_Call {
	_c.Call.Return(run)
	return _c
}
