// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bamsammich/docsearch/internal/domain"
	"github.com/bamsammich/docsearch/internal/service/document"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDocuments creates a new instance of MockDocuments. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDocuments(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDocuments {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDocuments{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDocuments is an autogenerated mock type for the Documents type
type MockDocuments struct {
	mock.Mock
}

type MockDocuments_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDocuments) EXPECT() *MockDocuments_Expecter {
	return &MockDocuments_Expecter{mock: &_m.Mock}
}

// Inspect provides a mock function for the type MockDocuments
func (_mock *MockDocuments) Inspect(ctx context.Context, target string) (*domain.InspectReport, error) {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 *domain.InspectReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.InspectReport, error)); ok {
		return returnFunc(ctx, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.InspectReport); ok {
		r0 = returnFunc(ctx, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.InspectReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocuments_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type MockDocuments_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockDocuments_Expecter) Inspect(ctx any, target any) *MockDocuments_Inspect_Call {
	return &MockDocuments_Inspect_Call{Call: _e.mock.On("Inspect", ctx, target)}
}

func (_c *MockDocuments_Inspect_Call) Run(run func(ctx context.Context, target string)) *MockDocuments_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDocuments_Inspect_Call) Return(inspectReport *domain.InspectReport, err error) *MockDocuments_Inspect_Call {
	_c.Call.Return(inspectReport, err)
	return _c
}

func (_c *MockDocuments_Inspect_Call) RunAndReturn(run func(ctx context.Context, target string) (*domain.InspectReport, error)) *MockDocuments_Inspect_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockDocuments
func (_mock *MockDocuments) List(ctx context.Context) ([]document.Document, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []document.Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]document.Document, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []document.Document); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]document.Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocuments_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockDocuments_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDocuments_Expecter) List(ctx any) *MockDocuments_List_Call {
	return &MockDocuments_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockDocuments_List_Call) Run(run func(ctx context.Context)) *MockDocuments_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDocuments_List_Call) Return(documents []document.Document, err error) *MockDocuments_List_Call {
	_c.Call.Return(documents, err)
	return _c
}

func (_c *MockDocuments_List_Call) RunAndReturn(run func(ctx context.Context) ([]document.Document, error)) *MockDocuments_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockDocuments
func (_mock *MockDocuments) Remove(ctx context.Context, docID string) error {
	ret := _mock.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, docID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDocuments_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockDocuments_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
func (_e *MockDocuments_Expecter) Remove(ctx any, docID any) *MockDocuments_Remove_Call {
	return &MockDocuments_Remove_Call{Call: _e.mock.On("Remove", ctx, docID)}
}

func (_c *MockDocuments_Remove_Call) Run(run func(ctx context.Context, docID string)) *MockDocuments_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDocuments_Remove_Call) Return(err error) *MockDocuments_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDocuments_Remove_Call) RunAndReturn(run func(ctx context.Context, docID string) error) *MockDocuments_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockDocuments
func (_mock *MockDocuments) Verify(ctx context.Context, docID string) (*document.VerifyReport, error) {
	ret := _mock.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 *document.VerifyReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*document.VerifyReport, error)); ok {
		return returnFunc(ctx, docID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *document.VerifyReport); ok {
		r0 = returnFunc(ctx, docID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*document.VerifyReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, docID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDocuments_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockDocuments_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
func (_e *MockDocuments_Expecter) Verify(ctx any, docID any) *MockDocuments_Verify_Call {
	return &MockDocuments_Verify_Call{Call: _e.mock.On("Verify", ctx, docID)}
}

func (_c *MockDocuments_Verify_Call) Run(run func(ctx context.Context, docID string)) *MockDocuments_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDocuments_Verify_Call) Return(verifyReport *document.VerifyReport, err error) *MockDocuments_Verify_Call {
	_c.Call.Return(verifyReport, err)
	return _c
}

func (_c *MockDocuments_Verify_Call) RunAndReturn(run func(ctx context.Context, docID string) (*document.VerifyReport, error)) *MockDocuments_Verify_Call {
	_c.Call.Return(run)
	return _c
}
