// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bamsammich/docsearch/internal/service/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobs creates a new instance of MockJobs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobs(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobs {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockJobs{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockJobs is an autogenerated mock type for the Jobs type
type MockJobs struct {
	mock.Mock
}

type MockJobs_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobs) EXPECT() *MockJobs_Expecter {
	return &MockJobs_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockJobs
func (_mock *MockJobs) Cancel(ctx context.Context, id int64) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobs_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockJobs_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *MockJobs_Expecter) Cancel(ctx any, id any) *MockJobs_Cancel_Call {
	return &MockJobs_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id)}
}

func (_c *MockJobs_Cancel_Call) Run(run func(ctx context.Context, id int64)) *MockJobs_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobs_Cancel_Call) Return(s string, err error) *MockJobs_Cancel_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJobs_Cancel_Call) RunAndReturn(run func(ctx context.Context, id int64) (string, error)) *MockJobs_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function for the type MockJobs
func (_mock *MockJobs) Enqueue(ctx context.Context, target string, title string) ([]job.Queued, error) {
	ret := _mock.Called(ctx, target, title)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 []job.Queued
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]job.Queued, error)); ok {
		return returnFunc(ctx, target, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []job.Queued); ok {
		r0 = returnFunc(ctx, target, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]job.Queued)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, target, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobs_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockJobs_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
//   - title string
func (_e *MockJobs_Expecter) Enqueue(ctx any, target any, title any) *MockJobs_Enqueue_Call {
	return &MockJobs_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, target, title)}
}

func (_c *MockJobs_Enqueue_Call) Run(run func(ctx context.Context, target string, title string)) *MockJobs_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobs_Enqueue_Call) Return(queueds []job.Queued, err error) *MockJobs_Enqueue_Call {
	_c.Call.Return(queueds, err)
	return _c
}

func (_c *MockJobs_Enqueue_Call) RunAndReturn(run func(ctx context.Context, target string, title string) ([]job.Queued, error)) *MockJobs_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockJobs
func (_mock *MockJobs) List(ctx context.Context, includeCompleted bool, limit int) ([]job.Job, error) {
	ret := _mock.Called(ctx, includeCompleted, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []job.Job
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, int) ([]job.Job, error)); ok {
		return returnFunc(ctx, includeCompleted, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, int) []job.Job); ok {
		r0 = returnFunc(ctx, includeCompleted, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]job.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, int) error); ok {
		r1 = returnFunc(ctx, includeCompleted, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobs_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockJobs_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - includeCompleted bool
//   - limit int
func (_e *MockJobs_Expecter) List(ctx any, includeCompleted any, limit any) *MockJobs_List_Call {
	return &MockJobs_List_Call{Call: _e.mock.On("List", ctx, includeCompleted, limit)}
}

func (_c *MockJobs_List_Call) Run(run func(ctx context.Context, includeCompleted bool, limit int)) *MockJobs_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobs_List_Call) Return(jobs []job.Job, err error) *MockJobs_List_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJobs_List_Call) RunAndReturn(run func(ctx context.Context, includeCompleted bool, limit int) ([]job.Job, error)) *MockJobs_List_Call {
	_c.Call.Return(run)
	return _c
}
