// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/bamsammich/docsearch/internal/service/ingest"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSources creates a new instance of MockSources. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSources(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSources {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockSources{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockSources is an autogenerated mock type for the Sources type
type MockSources struct {
	mock.Mock
}

type MockSources_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSources) EXPECT() *MockSources_Expecter {
	return &MockSources_Expecter{mock: &_m.Mock}
}

// For provides a mock function for the type MockSources
func (_mock *MockSources) For(source string, revalidate bool) (ingest.Source, error) {
	ret := _mock.Called(source, revalidate)

	if len(ret) == 0 {
		panic("no return value specified for For")
	}

	var r0 ingest.Source
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, bool) (ingest.Source, error)); ok {
		return returnFunc(source, revalidate)
	}
	if returnFunc, ok := ret.Get(0).(func(string, bool) ingest.Source); ok {
		r0 = returnFunc(source, revalidate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ingest.Source)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = returnFunc(source, revalidate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSources_For_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'For'
type MockSources_For_Call struct {
	*mock.Call
}

// For is a helper method to define mock.On call
//   - source string
//   - revalidate bool
func (_e *MockSources_Expecter) For(source any, revalidate any) *MockSources_For_Call {
	return &MockSources_For_Call{Call: _e.mock.On("For", source, revalidate)}
}

func (_c *MockSources_For_Call) Run(run func(source string, revalidate bool)) *MockSources_For_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSources_For_Call) Return(source1 ingest.Source, err error) *MockSources_For_Call {
	_c.Call.Return(source1, err)
	return _c
}

func (_c *MockSources_For_Call) RunAndReturn(run func(source string, revalidate bool) (ingest.Source, error)) *MockSources_For_Call {
	_c.Call.Return(run)
	return _c
}
