// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bamsammich/docsearch/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockInspector creates a new instance of MockInspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInspector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInspector {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockInspector{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockInspector is an autogenerated mock type for the Inspector type
type MockInspector struct {
	mock.Mock
}

type MockInspector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInspector) EXPECT() *MockInspector_Expecter {
	return &MockInspector_Expecter{mock: &_m.Mock}
}

// Inspect provides a mock function for the type MockInspector
func (_mock *MockInspector) Inspect(ctx context.Context, target string) (*domain.InspectReport, error) {
	ret := _mock.Called(ctx, target)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 *domain.InspectReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.InspectReport, error)); ok {
		return returnFunc(ctx, target)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.InspectReport); ok {
		r0 = returnFunc(ctx, target)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.InspectReport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, target)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInspector_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type MockInspector_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - target string
func (_e *MockInspector_Expecter) Inspect(ctx any, target any) *MockInspector_Inspect_Call {
	return &MockInspector_Inspect_Call{Call: _e.mock.On("Inspect", ctx, target)}
}

func (_c *MockInspector_Inspect_Call) Run(run func(ctx context.Context, target string)) *MockInspector_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInspector_Inspect_Call) Return(inspectReport *domain.InspectReport, err error) *MockInspector_Inspect_Call {
	_c.Call.Return(inspectReport, err)
	return _c
}

func (_c *MockInspector_Inspect_Call) RunAndReturn(run func(ctx context.Context, target string) (*domain.InspectReport, error)) *MockInspector_Inspect_Call {
	_c.Call.Return(run)
	return _c
}
