// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/bamsammich/docsearch/internal/domain"
	"github.com/bamsammich/docsearch/internal/service/document"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Chunks provides a mock function for the type MockRepository
func (_mock *MockRepository) Chunks(ctx context.Context, docID string) ([]domain.Chunk, error) {
	ret := _mock.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for Chunks")
	}

	var r0 []domain.Chunk
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.Chunk, error)); ok {
		return returnFunc(ctx, docID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.Chunk); ok {
		r0 = returnFunc(ctx, docID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Chunk)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, docID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Chunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chunks'
type MockRepository_Chunks_Call struct {
	*mock.Call
}

// Chunks is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
func (_e *MockRepository_Expecter) Chunks(ctx any, docID any) *MockRepository_Chunks_Call {
	return &MockRepository_Chunks_Call{Call: _e.mock.On("Chunks", ctx, docID)}
}

func (_c *MockRepository_Chunks_Call) Run(run func(ctx context.Context, docID string)) *MockRepository_Chunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Chunks_Call) Return(chunks []domain.Chunk, err error) *MockRepository_Chunks_Call {
	_c.Call.Return(chunks, err)
	return _c
}

func (_c *MockRepository_Chunks_Call) RunAndReturn(run func(ctx context.Context, docID string) ([]domain.Chunk, error)) *MockRepository_Chunks_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, docID string) error {
	ret := _mock.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, docID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
func (_e *MockRepository_Expecter) Delete(ctx any, docID any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, docID)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, docID string)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, docID string) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(ctx context.Context, docID string) (*document.Document, error) {
	ret := _mock.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *document.Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*document.Document, error)); ok {
		return returnFunc(ctx, docID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *document.Document); ok {
		r0 = returnFunc(ctx, docID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*document.Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, docID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
func (_e *MockRepository_Expecter) Get(ctx any, docID any) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", ctx, docID)}
}

func (_c *MockRepository_Get_Call) Run(run func(ctx context.Context, docID string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(document1 *document.Document, err error) *MockRepository_Get_Call {
	_c.Call.Return(document1, err)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(ctx context.Context, docID string) (*document.Document, error)) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// IndexTermSections provides a mock function for the type MockRepository
func (_mock *MockRepository) IndexTermSections(ctx context.Context, docID string) ([]string, error) {
	ret := _mock.Called(ctx, docID)

	if len(ret) == 0 {
		panic("no return value specified for IndexTermSections")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, docID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, docID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, docID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_IndexTermSections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexTermSections'
type MockRepository_IndexTermSections_Call struct {
	*mock.Call
}

// IndexTermSections is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
func (_e *MockRepository_Expecter) IndexTermSections(ctx any, docID any) *MockRepository_IndexTermSections_Call {
	return &MockRepository_IndexTermSections_Call{Call: _e.mock.On("IndexTermSections", ctx, docID)}
}

func (_c *MockRepository_IndexTermSections_Call) Run(run func(ctx context.Context, docID string)) *MockRepository_IndexTermSections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_IndexTermSections_Call) Return(strings []string, err error) *MockRepository_IndexTermSections_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockRepository_IndexTermSections_Call) RunAndReturn(run func(ctx context.Context, docID string) ([]string, error)) *MockRepository_IndexTermSections_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context) ([]document.Document, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []document.Document
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]document.Document, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []document.Document); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]document.Document)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) List(ctx any) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(documents []document.Document, err error) *MockRepository_List_Call {
	_c.Call.Return(documents, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]document.Document, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// SectionHasChunks provides a mock function for the type MockRepository
func (_mock *MockRepository) SectionHasChunks(ctx context.Context, docID string, section string) (bool, error) {
	ret := _mock.Called(ctx, docID, section)

	if len(ret) == 0 {
		panic("no return value specified for SectionHasChunks")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, docID, section)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, docID, section)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, docID, section)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_SectionHasChunks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SectionHasChunks'
type MockRepository_SectionHasChunks_Call struct {
	*mock.Call
}

// SectionHasChunks is a helper method to define mock.On call
//   - ctx context.Context
//   - docID string
//   - section string
func (_e *MockRepository_Expecter) SectionHasChunks(ctx any, docID any, section any) *MockRepository_SectionHasChunks_Call {
	return &MockRepository_SectionHasChunks_Call{Call: _e.mock.On("SectionHasChunks", ctx, docID, section)}
}

func (_c *MockRepository_SectionHasChunks_Call) Run(run func(ctx context.Context, docID string, section string)) *MockRepository_SectionHasChunks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_SectionHasChunks_Call) Return(b bool, err error) *MockRepository_SectionHasChunks_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockRepository_SectionHasChunks_Call) RunAndReturn(run func(ctx context.Context, docID string, section string) (bool, error)) *MockRepository_SectionHasChunks_Call {
	_c.Call.Return(run)
	return _c
}
