// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package pgdbgen

import (
	"context"
	"database/sql"
	"time"
)

const cachedResponse = `-- name: CachedResponse :one

SELECT url, final_url, status, content_type, etag, last_modified, body, sha256,
       fetched_at
  FROM responses WHERE url = $1
`

type CachedResponseRow struct {
	Url          string
	FinalUrl     string
	Status       int32
	ContentType  sql.NullString
	Etag         sql.NullString
	LastModified sql.NullString
	Body         []byte
	Sha256       string
	FetchedAt    time.Time
}

// The crawl's response cache, read and written by the worker through
// internal/site/fetch/pgcache.
//
// Nothing a search reads is here. The cache holds raw HTTP responses so that
// a cancelled crawl resumes, a refresh can send conditional requests, and
// re-chunking a site makes none.
//
// Every statement runs in a transaction that opened with
// SET LOCAL app.user_id, so a read names no user and the policy decides what
// it sees. A write names user_id because a row has to carry its owner.
func (q *Queries) CachedResponse(ctx context.Context, url string) (CachedResponseRow, error) {
	row := q.db.QueryRowContext(ctx, cachedResponse, url)
	var i CachedResponseRow
	err := row.Scan(
		&i.Url,
		&i.FinalUrl,
		&i.Status,
		&i.ContentType,
		&i.Etag,
		&i.LastModified,
		&i.Body,
		&i.Sha256,
		&i.FetchedAt,
	)
	return i, err
}

const cachedRobots = `-- name: CachedRobots :one
SELECT body, fetched_at FROM robots WHERE host = $1
`

type CachedRobotsRow struct {
	Body      string
	FetchedAt time.Time
}

func (q *Queries) CachedRobots(ctx context.Context, host string) (CachedRobotsRow, error) {
	row := q.db.QueryRowContext(ctx, cachedRobots, host)
	var i CachedRobotsRow
	err := row.Scan(&i.Body, &i.FetchedAt)
	return i, err
}

const storeResponse = `-- name: StoreResponse :exec
INSERT INTO responses (
  user_id, url, final_url, status, content_type, etag, last_modified, body,
  sha256, fetched_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id, url) DO UPDATE SET
  final_url = EXCLUDED.final_url,
  status = EXCLUDED.status,
  content_type = EXCLUDED.content_type,
  etag = EXCLUDED.etag,
  last_modified = EXCLUDED.last_modified,
  body = EXCLUDED.body,
  sha256 = EXCLUDED.sha256,
  fetched_at = EXCLUDED.fetched_at
`

type StoreResponseParams struct {
	UserID       string
	Url          string
	FinalUrl     string
	Status       int32
	ContentType  sql.NullString
	Etag         sql.NullString
	LastModified sql.NullString
	Body         []byte
	Sha256       string
	FetchedAt    time.Time
}

// A URL fetched again replaces what was stored for it, which is what makes a
// refresh idempotent.
func (q *Queries) StoreResponse(ctx context.Context, arg StoreResponseParams) error {
	_, err := q.db.ExecContext(ctx, storeResponse,
		arg.UserID,
		arg.Url,
		arg.FinalUrl,
		arg.Status,
		arg.ContentType,
		arg.Etag,
		arg.LastModified,
		arg.Body,
		arg.Sha256,
		arg.FetchedAt,
	)
	return err
}

const storeRobots = `-- name: StoreRobots :exec
INSERT INTO robots (user_id, host, body, fetched_at) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, host) DO UPDATE SET
  body = EXCLUDED.body, fetched_at = EXCLUDED.fetched_at
`

type StoreRobotsParams struct {
	UserID    string
	Host      string
	Body      string
	FetchedAt time.Time
}

// The crawler supplies the time rather than the database, because the crawler
// is what compares the file's age against the 24 hours RFC 9309 allows. Read
// from one clock and written by another, the comparison would answer to the
// skew between a worker and its database.
func (q *Queries) StoreRobots(ctx context.Context, arg StoreRobotsParams) error {
	_, err := q.db.ExecContext(ctx, storeRobots,
		arg.UserID,
		arg.Host,
		arg.Body,
		arg.FetchedAt,
	)
	return err
}

const touchResponse = `-- name: TouchResponse :exec
UPDATE responses SET fetched_at = now() WHERE url = $1
`

// A conditional request that came back 304 confirms the stored copy, so only
// its age changes. The database's clock is good enough here, because nothing
// measures how old a response is; a robots.txt is the opposite case.
func (q *Queries) TouchResponse(ctx context.Context, url string) error {
	_, err := q.db.ExecContext(ctx, touchResponse, url)
	return err
}
