// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package pgdbgen

import (
	"context"
	"database/sql"
)

const documentStatus = `-- name: DocumentStatus :one
SELECT status FROM documents WHERE doc_id = $1
`

func (q *Queries) DocumentStatus(ctx context.Context, docID string) (string, error) {
	row := q.db.QueryRowContext(ctx, documentStatus, docID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listReadyDocuments = `-- name: ListReadyDocuments :many
SELECT doc_id, title, format, source_kind, page_count, chunk_count, warnings
  FROM documents
 WHERE status = 'ready'
 ORDER BY doc_id
`

type ListReadyDocumentsRow struct {
	DocID      string
	Title      string
	Format     string
	SourceKind string
	PageCount  sql.NullInt32
	ChunkCount sql.NullInt32
	Warnings   sql.NullString
}

func (q *Queries) ListReadyDocuments(ctx context.Context) ([]ListReadyDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReadyDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReadyDocumentsRow{}
	for rows.Next() {
		var i ListReadyDocumentsRow
		if err := rows.Scan(
			&i.DocID,
			&i.Title,
			&i.Format,
			&i.SourceKind,
			&i.PageCount,
			&i.ChunkCount,
			&i.Warnings,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const schemaVersion = `-- name: SchemaVersion :one
SELECT version FROM schema_version LIMIT 1
`

func (q *Queries) SchemaVersion(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, schemaVersion)
	var version int32
	err := row.Scan(&version)
	return version, err
}
