// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package pgdbgen

import (
	"context"
	"database/sql"
)

const completeJob = `-- name: CompleteJob :exec
UPDATE ingest_jobs
   SET status = 'done', phase = NULL, doc_id = $1, error = NULL, warnings = $2,
       lease_until = NULL, updated_at = now()
 WHERE id = $3
`

type CompleteJobParams struct {
	DocID    sql.NullString
	Warnings sql.NullString
	ID       int64
}

// Run in the same transaction as MarkDocumentReady, so a document can never
// be searchable while the job that wrote it still reads as running.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.DocID, arg.Warnings, arg.ID)
	return err
}

const countDocumentChunks = `-- name: CountDocumentChunks :one
SELECT COUNT(*) FROM chunks WHERE doc_id = $1
`

func (q *Queries) CountDocumentChunks(ctx context.Context, docID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentChunks, docID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDocumentChunks = `-- name: DeleteDocumentChunks :exec
DELETE FROM chunks WHERE doc_id = $1
`

// Ordering matters, because every one of these tables references documents:
// deleting the document row first is refused by the foreign key. Chunks go
// first for the same reason pages and index terms do.
func (q *Queries) DeleteDocumentChunks(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentChunks, docID)
	return err
}

const deleteDocumentIndexTerms = `-- name: DeleteDocumentIndexTerms :exec
DELETE FROM index_terms WHERE doc_id = $1
`

func (q *Queries) DeleteDocumentIndexTerms(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentIndexTerms, docID)
	return err
}

const deleteDocumentPages = `-- name: DeleteDocumentPages :exec
DELETE FROM pages WHERE doc_id = $1
`

func (q *Queries) DeleteDocumentPages(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentPages, docID)
	return err
}

const deleteDocumentRow = `-- name: DeleteDocumentRow :exec
DELETE FROM documents WHERE doc_id = $1
`

func (q *Queries) DeleteDocumentRow(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentRow, docID)
	return err
}

const docIDForSourcePath = `-- name: DocIDForSourcePath :one
SELECT doc_id FROM documents WHERE source_path = $1
`

func (q *Queries) DocIDForSourcePath(ctx context.Context, sourcePath string) (string, error) {
	row := q.db.QueryRowContext(ctx, docIDForSourcePath, sourcePath)
	var doc_id string
	err := row.Scan(&doc_id)
	return doc_id, err
}

const docIDsWithPrefix = `-- name: DocIDsWithPrefix :many
SELECT doc_id FROM documents WHERE doc_id LIKE $1
`

func (q *Queries) DocIDsWithPrefix(ctx context.Context, docID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, docIDsWithPrefix, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var doc_id string
		if err := rows.Scan(&doc_id); err != nil {
			return nil, err
		}
		items = append(items, doc_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const documentByID = `-- name: DocumentByID :one
SELECT doc_id, title, format, source_kind, status, page_count, chunk_count, warnings
  FROM documents WHERE doc_id = $1
`

type DocumentByIDRow struct {
	DocID      string
	Title      string
	Format     string
	SourceKind string
	Status     string
	PageCount  sql.NullInt32
	ChunkCount sql.NullInt32
	Warnings   sql.NullString
}

func (q *Queries) DocumentByID(ctx context.Context, docID string) (DocumentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, documentByID, docID)
	var i DocumentByIDRow
	err := row.Scan(
		&i.DocID,
		&i.Title,
		&i.Format,
		&i.SourceKind,
		&i.Status,
		&i.PageCount,
		&i.ChunkCount,
		&i.Warnings,
	)
	return i, err
}

const documentChunks = `-- name: DocumentChunks :many
SELECT ordinal, section, page_start, page_end, printed_page_start,
       image_count, kind, url, fragment, heading_path, text
  FROM chunks
 WHERE doc_id = $1
 ORDER BY ordinal
`

type DocumentChunksRow struct {
	Ordinal          int32
	Section          sql.NullString
	PageStart        sql.NullInt32
	PageEnd          sql.NullInt32
	PrintedPageStart sql.NullInt32
	ImageCount       int32
	Kind             string
	Url              sql.NullString
	Fragment         sql.NullString
	HeadingPath      string
	Text             string
}

// Verification reads every column, because what it checks is whether the
// columns agree with each other.
func (q *Queries) DocumentChunks(ctx context.Context, docID string) ([]DocumentChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, documentChunks, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentChunksRow{}
	for rows.Next() {
		var i DocumentChunksRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.Section,
			&i.PageStart,
			&i.PageEnd,
			&i.PrintedPageStart,
			&i.ImageCount,
			&i.Kind,
			&i.Url,
			&i.Fragment,
			&i.HeadingPath,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const indexTermCount = `-- name: IndexTermCount :one
SELECT COUNT(*) FROM index_terms WHERE doc_id = $1
`

// Entries, not sections: the verify report counts what the back-of-book
// index holds, and many entries point at one section.
func (q *Queries) IndexTermCount(ctx context.Context, docID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, indexTermCount, docID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const indexTermSections = `-- name: IndexTermSections :many
SELECT DISTINCT section FROM index_terms WHERE doc_id = $1 ORDER BY section
`

func (q *Queries) IndexTermSections(ctx context.Context, docID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, indexTermSections, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var section string
		if err := rows.Scan(&section); err != nil {
			return nil, err
		}
		items = append(items, section)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO chunks (
  user_id, doc_id, ordinal, section, page_start, page_end, printed_page_start,
  image_count, kind, url, fragment, heading_path, text
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertChunkParams struct {
	UserID           string
	DocID            string
	Ordinal          int32
	Section          sql.NullString
	PageStart        sql.NullInt32
	PageEnd          sql.NullInt32
	PrintedPageStart sql.NullInt32
	ImageCount       int32
	Kind             string
	Url              sql.NullString
	Fragment         sql.NullString
	HeadingPath      string
	Text             string
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.db.ExecContext(ctx, insertChunk,
		arg.UserID,
		arg.DocID,
		arg.Ordinal,
		arg.Section,
		arg.PageStart,
		arg.PageEnd,
		arg.PrintedPageStart,
		arg.ImageCount,
		arg.Kind,
		arg.Url,
		arg.Fragment,
		arg.HeadingPath,
		arg.Text,
	)
	return err
}

const insertDocument = `-- name: InsertDocument :exec
INSERT INTO documents (
  user_id, doc_id, title, format, source_path, source_kind, sha256,
  page_count, chunk_count, status, ingested_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NULL, 'ingesting', NULL)
`

type InsertDocumentParams struct {
	UserID     string
	DocID      string
	Title      string
	Format     string
	SourcePath string
	SourceKind string
	Sha256     string
	PageCount  sql.NullInt32
}

// A document is born 'ingesting' with no chunk count and no timestamp, so
// every read path, which filters on status = 'ready', passes over it until
// MarkDocumentReady runs.
func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, insertDocument,
		arg.UserID,
		arg.DocID,
		arg.Title,
		arg.Format,
		arg.SourcePath,
		arg.SourceKind,
		arg.Sha256,
		arg.PageCount,
	)
	return err
}

const insertIndexTerm = `-- name: InsertIndexTerm :exec
INSERT INTO index_terms (user_id, doc_id, term, section) VALUES ($1, $2, $3, $4)
`

type InsertIndexTermParams struct {
	UserID  string
	DocID   string
	Term    string
	Section string
}

func (q *Queries) InsertIndexTerm(ctx context.Context, arg InsertIndexTermParams) error {
	_, err := q.db.ExecContext(ctx, insertIndexTerm,
		arg.UserID,
		arg.DocID,
		arg.Term,
		arg.Section,
	)
	return err
}

const markDocumentReady = `-- name: MarkDocumentReady :exec
UPDATE documents
   SET status = 'ready', chunk_count = $1, ingested_at = $2, warnings = $3
 WHERE doc_id = $4
`

type MarkDocumentReadyParams struct {
	ChunkCount sql.NullInt32
	IngestedAt sql.NullTime
	Warnings   sql.NullString
	DocID      string
}

// The moment a document becomes visible to search.
func (q *Queries) MarkDocumentReady(ctx context.Context, arg MarkDocumentReadyParams) error {
	_, err := q.db.ExecContext(ctx, markDocumentReady,
		arg.ChunkCount,
		arg.IngestedAt,
		arg.Warnings,
		arg.DocID,
	)
	return err
}

const readyDocumentWithDigest = `-- name: ReadyDocumentWithDigest :one

SELECT doc_id, title FROM documents WHERE sha256 = $1 AND status = 'ready'
`

type ReadyDocumentWithDigestRow struct {
	DocID string
	Title string
}

// Writes the ingest service makes, through internal/repository/postgres.
//
// Reads the server makes live in documents.sql, chunks.sql and jobs.sql. The
// split is by who runs the statement, not by which table it names: the worker
// writes a document incrementally and the server must not see it until the
// last statement here flips its status.
//
// Every statement runs in a transaction that opened with
// SET LOCAL app.user_id, so row-level security scopes it to one library. A
// read therefore names no user: the policy is where that is decided, and a
// second copy of the filter in 45 queries is 45 places for it to be wrong.
// A write names user_id because a row has to carry its owner, and the policy
// then refuses a value that disagrees with the session.
func (q *Queries) ReadyDocumentWithDigest(ctx context.Context, sha256 string) (ReadyDocumentWithDigestRow, error) {
	row := q.db.QueryRowContext(ctx, readyDocumentWithDigest, sha256)
	var i ReadyDocumentWithDigestRow
	err := row.Scan(&i.DocID, &i.Title)
	return i, err
}

const sectionHasChunks = `-- name: SectionHasChunks :one
SELECT EXISTS(
  SELECT 1 FROM chunks
   WHERE doc_id = $1 AND (chunks.section = $2 OR chunks.section LIKE $2 || '.%'))
`

type SectionHasChunksParams struct {
	DocID   string
	Section sql.NullString
}

// Subtree semantics, the same clause ChunksInSection uses: an index entry
// pointing at chapter 4 refers to the whole chapter.
func (q *Queries) SectionHasChunks(ctx context.Context, arg SectionHasChunksParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, sectionHasChunks, arg.DocID, arg.Section)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertPage = `-- name: UpsertPage :exec
INSERT INTO pages (user_id, doc_id, page, text) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, doc_id, page) DO UPDATE SET text = EXCLUDED.text
`

type UpsertPageParams struct {
	UserID string
	DocID  string
	Page   int32
	Text   string
}

// A page arrives again when a site is re-crawled, so the write is an upsert
// rather than an insert that has to be preceded by a delete.
func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertPage,
		arg.UserID,
		arg.DocID,
		arg.Page,
		arg.Text,
	)
	return err
}
