// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdbgen

import (
	"database/sql"
	"time"
)

type Chunk struct {
	UserID           string
	ID               int64
	DocID            string
	Ordinal          int32
	Section          sql.NullString
	PageStart        sql.NullInt32
	PageEnd          sql.NullInt32
	PrintedPageStart sql.NullInt32
	ImageCount       int32
	Kind             string
	Url              sql.NullString
	Fragment         sql.NullString
	HeadingPath      string
	Text             string
}

type ChunksDefault struct {
	UserID           string
	ID               int64
	DocID            string
	Ordinal          int32
	Section          sql.NullString
	PageStart        sql.NullInt32
	PageEnd          sql.NullInt32
	PrintedPageStart sql.NullInt32
	ImageCount       int32
	Kind             string
	Url              sql.NullString
	Fragment         sql.NullString
	HeadingPath      string
	Text             string
}

type Document struct {
	DocID      string
	Title      string
	Format     string
	SourcePath string
	SourceKind string
	Sha256     string
	PageCount  sql.NullInt32
	ChunkCount sql.NullInt32
	Status     string
	IngestedAt sql.NullTime
	Warnings   sql.NullString
	UserID     string
}

type IndexTerm struct {
	DocID   string
	Term    string
	Section string
	UserID  string
}

type IngestJob struct {
	ID          int64
	SourcePath  string
	Title       sql.NullString
	DocID       sql.NullString
	Status      string
	Phase       sql.NullString
	ProgressCur sql.NullInt32
	ProgressTot sql.NullInt32
	Attempts    int32
	Permanent   bool
	CancelReq   bool
	Error       sql.NullString
	Warnings    sql.NullString
	LeaseUntil  sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	UserID      string
}

type Page struct {
	DocID  string
	Page   int32
	Text   string
	UserID string
}

type SchemaVersion struct {
	Version   int32
	AppliedAt time.Time
}

type User struct {
	UserID    string
	CreatedAt time.Time
}
