-- The schema a fully migrated database holds, written by
-- `mise run generate` as pg_dump renders it.
--
-- Reference only. Nothing reads this file: the migrations in
-- internal/schema/migrations are what build a database, and this is what
-- they add up to. It exists so a review can see the whole shape at once, and
-- so a schema change shows up as a diff of the destination rather than only
-- as a diff of the step.
--
-- PostgreSQL database dump
--




--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';



--
-- Name: chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chunks (
    user_id text NOT NULL,
    id bigint NOT NULL,
    doc_id text NOT NULL,
    ordinal integer NOT NULL,
    section text,
    page_start integer,
    page_end integer,
    printed_page_start integer,
    image_count integer DEFAULT 0 NOT NULL,
    kind text DEFAULT 'prose'::text NOT NULL,
    url text,
    fragment text,
    heading_path text NOT NULL,
    text text NOT NULL
)
PARTITION BY LIST (user_id);

ALTER TABLE ONLY public.chunks FORCE ROW LEVEL SECURITY;



--
-- Name: chunks_default; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chunks_default (
    user_id text NOT NULL,
    id bigint NOT NULL,
    doc_id text NOT NULL,
    ordinal integer NOT NULL,
    section text,
    page_start integer,
    page_end integer,
    printed_page_start integer,
    image_count integer DEFAULT 0 NOT NULL,
    kind text DEFAULT 'prose'::text NOT NULL,
    url text,
    fragment text,
    heading_path text NOT NULL,
    text text NOT NULL
);


--
-- Name: chunks_id_seq1; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chunks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chunks_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    doc_id text NOT NULL,
    title text NOT NULL,
    format text NOT NULL,
    source_path text NOT NULL,
    source_kind text DEFAULT 'file'::text NOT NULL,
    sha256 text NOT NULL,
    page_count integer,
    chunk_count integer,
    status text NOT NULL,
    ingested_at timestamp with time zone,
    warnings text,
    user_id text NOT NULL
);

ALTER TABLE ONLY public.documents FORCE ROW LEVEL SECURITY;


--
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: index_terms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.index_terms (
    doc_id text NOT NULL,
    term text NOT NULL,
    section text NOT NULL,
    user_id text NOT NULL
);

ALTER TABLE ONLY public.index_terms FORCE ROW LEVEL SECURITY;


--
-- Name: ingest_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ingest_jobs (
    id bigint NOT NULL,
    source_path text NOT NULL,
    title text,
    doc_id text,
    status text NOT NULL,
    phase text,
    progress_cur integer,
    progress_tot integer,
    attempts integer DEFAULT 0 NOT NULL,
    permanent boolean DEFAULT false NOT NULL,
    cancel_req boolean DEFAULT false NOT NULL,
    error text,
    warnings text,
    lease_until timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id text NOT NULL
);

ALTER TABLE ONLY public.ingest_jobs FORCE ROW LEVEL SECURITY;


--
-- Name: ingest_jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ingest_jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ingest_jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pages (
    doc_id text NOT NULL,
    page integer NOT NULL,
    text text NOT NULL,
    user_id text NOT NULL
);

ALTER TABLE ONLY public.pages FORCE ROW LEVEL SECURITY;


--
-- Name: responses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.responses (
    user_id text NOT NULL,
    url text NOT NULL,
    final_url text NOT NULL,
    status integer NOT NULL,
    content_type text,
    etag text,
    last_modified text,
    body bytea NOT NULL,
    sha256 text NOT NULL,
    fetched_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY public.responses FORCE ROW LEVEL SECURITY;


--
-- Name: robots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.robots (
    user_id text NOT NULL,
    host text NOT NULL,
    body text NOT NULL,
    fetched_at timestamp with time zone NOT NULL
);

ALTER TABLE ONLY public.robots FORCE ROW LEVEL SECURITY;


--
-- Name: schema_version; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_version (
    version integer NOT NULL,
    applied_at timestamp with time zone NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: chunks_default; Type: TABLE ATTACH; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks ATTACH PARTITION public.chunks_default FOR VALUES IN ('default');


--
-- Name: chunks chunks_pkey1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks
    ADD CONSTRAINT chunks_pkey1 PRIMARY KEY (user_id, id);


--
-- Name: chunks_default chunks_default_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chunks_default
    ADD CONSTRAINT chunks_default_pkey PRIMARY KEY (user_id, id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (user_id, doc_id);


--
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- Name: ingest_jobs ingest_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ingest_jobs
    ADD CONSTRAINT ingest_jobs_pkey PRIMARY KEY (id);


--
-- Name: pages pages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pages
    ADD CONSTRAINT pages_pkey PRIMARY KEY (user_id, doc_id, page);


--
-- Name: responses responses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.responses
    ADD CONSTRAINT responses_pkey PRIMARY KEY (user_id, url);


--
-- Name: robots robots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robots
    ADD CONSTRAINT robots_pkey PRIMARY KEY (user_id, host);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: chunks_bm25; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_bm25 ON ONLY public.chunks USING bm25 ((((((heading_path || ' '::text) || heading_path) || ' '::text) || text))) WITH (text_config=simple);


--
-- Name: chunks_default_expr_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_default_expr_idx ON public.chunks_default USING bm25 ((((((heading_path || ' '::text) || heading_path) || ' '::text) || text))) WITH (text_config=simple);


--
-- Name: idx_chunks_doc_ord; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_doc_ord ON ONLY public.chunks USING btree (user_id, doc_id, ordinal);


--
-- Name: chunks_default_user_id_doc_id_ordinal_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_default_user_id_doc_id_ordinal_idx ON public.chunks_default USING btree (user_id, doc_id, ordinal);


--
-- Name: idx_chunks_doc_section; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunks_doc_section ON ONLY public.chunks USING btree (user_id, doc_id, section);


--
-- Name: chunks_default_user_id_doc_id_section_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chunks_default_user_id_doc_id_section_idx ON public.chunks_default USING btree (user_id, doc_id, section);


--
-- Name: idx_documents_sha; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_documents_sha ON public.documents USING btree (sha256);


--
-- Name: idx_documents_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_documents_source ON public.documents USING btree (source_path);


--
-- Name: idx_index_terms; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_index_terms ON public.index_terms USING btree (doc_id, term);


--
-- Name: idx_jobs_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_jobs_status ON public.ingest_jobs USING btree (status, created_at);


--
-- Name: chunks_default_expr_idx; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.chunks_bm25 ATTACH PARTITION public.chunks_default_expr_idx;


--
-- Name: chunks_default_pkey; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.chunks_pkey1 ATTACH PARTITION public.chunks_default_pkey;


--
-- Name: chunks_default_user_id_doc_id_ordinal_idx; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.idx_chunks_doc_ord ATTACH PARTITION public.chunks_default_user_id_doc_id_ordinal_idx;


--
-- Name: chunks_default_user_id_doc_id_section_idx; Type: INDEX ATTACH; Schema: public; Owner: -
--

ALTER INDEX public.idx_chunks_doc_section ATTACH PARTITION public.chunks_default_user_id_doc_id_section_idx;


--
-- Name: chunks chunks_user_id_doc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE public.chunks
    ADD CONSTRAINT chunks_user_id_doc_id_fkey FOREIGN KEY (user_id, doc_id) REFERENCES public.documents(user_id, doc_id);


--
-- Name: documents documents_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_user_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: index_terms index_terms_doc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.index_terms
    ADD CONSTRAINT index_terms_doc_fkey FOREIGN KEY (user_id, doc_id) REFERENCES public.documents(user_id, doc_id);


--
-- Name: pages pages_doc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pages
    ADD CONSTRAINT pages_doc_fkey FOREIGN KEY (user_id, doc_id) REFERENCES public.documents(user_id, doc_id);


--
-- Name: responses responses_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.responses
    ADD CONSTRAINT responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: robots robots_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.robots
    ADD CONSTRAINT robots_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: chunks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.chunks ENABLE ROW LEVEL SECURITY;

--
-- Name: documents; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

--
-- Name: index_terms; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.index_terms ENABLE ROW LEVEL SECURITY;

--
-- Name: ingest_jobs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.ingest_jobs ENABLE ROW LEVEL SECURITY;

--
-- Name: chunks own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY own ON public.chunks USING ((user_id = current_setting('app.user_id'::text, true))) WITH CHECK ((user_id = current_setting('app.user_id'::text, true)));


--
-- Name: documents own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY own ON public.documents USING ((user_id = current_setting('app.user_id'::text, true))) WITH CHECK ((user_id = current_setting('app.user_id'::text, true)));


--
-- Name: index_terms own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY own ON public.index_terms USING ((user_id = current_setting('app.user_id'::text, true))) WITH CHECK ((user_id = current_setting('app.user_id'::text, true)));


--
-- Name: ingest_jobs own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY own ON public.ingest_jobs USING ((user_id = current_setting('app.user_id'::text, true))) WITH CHECK ((user_id = current_setting('app.user_id'::text, true)));


--
-- Name: pages own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY own ON public.pages USING ((user_id = current_setting('app.user_id'::text, true))) WITH CHECK ((user_id = current_setting('app.user_id'::text, true)));


--
-- Name: responses own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY own ON public.responses USING ((user_id = current_setting('app.user_id'::text, true))) WITH CHECK ((user_id = current_setting('app.user_id'::text, true)));


--
-- Name: robots own; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY own ON public.robots USING ((user_id = current_setting('app.user_id'::text, true))) WITH CHECK ((user_id = current_setting('app.user_id'::text, true)));


--
-- Name: pages; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;

--
-- Name: responses; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.responses ENABLE ROW LEVEL SECURITY;

--
-- Name: robots; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.robots ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--


