// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: docsearch/type/v1/common.proto

// Package docsearch.type.v1 holds what more than one service says.
//
// A grade means the same thing to an ingest reporting what it just wrote and
// to a verification reporting what it found, so it is declared once. Each
// enum shares its numbering with docsearch's own, which is what makes the
// conversion at the boundary a cast rather than a lookup table that can
// drift.

package typev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Quality grades a document's derived structure.
type Quality int32

const (
	Quality_QUALITY_UNSPECIFIED Quality = 0
	Quality_QUALITY_OK          Quality = 1
	Quality_QUALITY_DEGRADED    Quality = 2
	Quality_QUALITY_FAILED      Quality = 3
)

// Enum value maps for Quality.
var (
	Quality_name = map[int32]string{
		0: "QUALITY_UNSPECIFIED",
		1: "QUALITY_OK",
		2: "QUALITY_DEGRADED",
		3: "QUALITY_FAILED",
	}
	Quality_value = map[string]int32{
		"QUALITY_UNSPECIFIED": 0,
		"QUALITY_OK":          1,
		"QUALITY_DEGRADED":    2,
		"QUALITY_FAILED":      3,
	}
)

func (x Quality) Enum() *Quality {
	p := new(Quality)
	*p = x
	return p
}

func (x Quality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Quality) Descriptor() protoreflect.EnumDescriptor {
	return file_docsearch_type_v1_common_proto_enumTypes[0].Descriptor()
}

func (Quality) Type() protoreflect.EnumType {
	return &file_docsearch_type_v1_common_proto_enumTypes[0]
}

func (x Quality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Quality.Descriptor instead.
func (Quality) EnumDescriptor() ([]byte, []int) {
	return file_docsearch_type_v1_common_proto_rawDescGZIP(), []int{0}
}

// SourceKind says what a document was read from.
type SourceKind int32

const (
	SourceKind_SOURCE_KIND_UNSPECIFIED SourceKind = 0
	SourceKind_SOURCE_KIND_FILE        SourceKind = 1
	SourceKind_SOURCE_KIND_SITE        SourceKind = 2
)

// Enum value maps for SourceKind.
var (
	SourceKind_name = map[int32]string{
		0: "SOURCE_KIND_UNSPECIFIED",
		1: "SOURCE_KIND_FILE",
		2: "SOURCE_KIND_SITE",
	}
	SourceKind_value = map[string]int32{
		"SOURCE_KIND_UNSPECIFIED": 0,
		"SOURCE_KIND_FILE":        1,
		"SOURCE_KIND_SITE":        2,
	}
)

func (x SourceKind) Enum() *SourceKind {
	p := new(SourceKind)
	*p = x
	return p
}

func (x SourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_docsearch_type_v1_common_proto_enumTypes[1].Descriptor()
}

func (SourceKind) Type() protoreflect.EnumType {
	return &file_docsearch_type_v1_common_proto_enumTypes[1]
}

func (x SourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceKind.Descriptor instead.
func (SourceKind) EnumDescriptor() ([]byte, []int) {
	return file_docsearch_type_v1_common_proto_rawDescGZIP(), []int{1}
}

// Verdict is how usable a document's chunks are.
//
// Separate from whether the rows are sound: a document can be perfectly
// consistent and still be shaped so retrieval cannot work on it.
type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_GOOD        Verdict = 1
	Verdict_VERDICT_DEGRADED    Verdict = 2
	Verdict_VERDICT_UNUSABLE    Verdict = 3
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_GOOD",
		2: "VERDICT_DEGRADED",
		3: "VERDICT_UNUSABLE",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_GOOD":        1,
		"VERDICT_DEGRADED":    2,
		"VERDICT_UNUSABLE":    3,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_docsearch_type_v1_common_proto_enumTypes[2].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_docsearch_type_v1_common_proto_enumTypes[2]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_docsearch_type_v1_common_proto_rawDescGZIP(), []int{2}
}

// Level is how much a reconnaissance finding matters.
type Level int32

const (
	Level_LEVEL_UNSPECIFIED Level = 0
	// A question answered well.
	Level_LEVEL_OK Level = 1
	// The document will ingest, and will search worse for what the finding
	// names.
	Level_LEVEL_WARN Level = 2
	// Ingest would refuse the document, or should.
	Level_LEVEL_BLOCKED Level = 3
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_UNSPECIFIED",
		1: "LEVEL_OK",
		2: "LEVEL_WARN",
		3: "LEVEL_BLOCKED",
	}
	Level_value = map[string]int32{
		"LEVEL_UNSPECIFIED": 0,
		"LEVEL_OK":          1,
		"LEVEL_WARN":        2,
		"LEVEL_BLOCKED":     3,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_docsearch_type_v1_common_proto_enumTypes[3].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_docsearch_type_v1_common_proto_enumTypes[3]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_docsearch_type_v1_common_proto_rawDescGZIP(), []int{3}
}

var File_docsearch_type_v1_common_proto protoreflect.FileDescriptor

const file_docsearch_type_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1edocsearch/type/v1/common.proto\x12\x11docsearch.type.v1*\\\n" +
	"\aQuality\x12\x17\n" +
	"\x13QUALITY_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"QUALITY_OK\x10\x01\x12\x14\n" +
	"\x10QUALITY_DEGRADED\x10\x02\x12\x12\n" +
	"\x0eQUALITY_FAILED\x10\x03*U\n" +
	"\n" +
	"SourceKind\x12\x1b\n" +
	"\x17SOURCE_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SOURCE_KIND_FILE\x10\x01\x12\x14\n" +
	"\x10SOURCE_KIND_SITE\x10\x02*`\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fVERDICT_GOOD\x10\x01\x12\x14\n" +
	"\x10VERDICT_DEGRADED\x10\x02\x12\x14\n" +
	"\x10VERDICT_UNUSABLE\x10\x03*O\n" +
	"\x05Level\x12\x15\n" +
	"\x11LEVEL_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bLEVEL_OK\x10\x01\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x02\x12\x11\n" +
	"\rLEVEL_BLOCKED\x10\x03B\xd1\x01\n" +
	"\x15com.docsearch.type.v1B\vCommonProtoP\x01ZEgithub.com/bamsammich/docsearch/internal/api/docsearch/type/v1;typev1\xa2\x02\x03DTX\xaa\x02\x11Docsearch.Type.V1\xca\x02\x11Docsearch\\Type\\V1\xe2\x02\x1dDocsearch\\Type\\V1\\GPBMetadata\xea\x02\x13Docsearch::Type::V1b\x06proto3"

var (
	file_docsearch_type_v1_common_proto_rawDescOnce sync.Once
	file_docsearch_type_v1_common_proto_rawDescData []byte
)

func file_docsearch_type_v1_common_proto_rawDescGZIP() []byte {
	file_docsearch_type_v1_common_proto_rawDescOnce.Do(func() {
		file_docsearch_type_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docsearch_type_v1_common_proto_rawDesc), len(file_docsearch_type_v1_common_proto_rawDesc)))
	})
	return file_docsearch_type_v1_common_proto_rawDescData
}

var file_docsearch_type_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_docsearch_type_v1_common_proto_goTypes = []any{
	(Quality)(0),    // 0: docsearch.type.v1.Quality
	(SourceKind)(0), // 1: docsearch.type.v1.SourceKind
	(Verdict)(0),    // 2: docsearch.type.v1.Verdict
	(Level)(0),      // 3: docsearch.type.v1.Level
}
var file_docsearch_type_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_docsearch_type_v1_common_proto_init() }
func file_docsearch_type_v1_common_proto_init() {
	if File_docsearch_type_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docsearch_type_v1_common_proto_rawDesc), len(file_docsearch_type_v1_common_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_docsearch_type_v1_common_proto_goTypes,
		DependencyIndexes: file_docsearch_type_v1_common_proto_depIdxs,
		EnumInfos:         file_docsearch_type_v1_common_proto_enumTypes,
	}.Build()
	File_docsearch_type_v1_common_proto = out.File
	file_docsearch_type_v1_common_proto_goTypes = nil
	file_docsearch_type_v1_common_proto_depIdxs = nil
}
