// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: docsearch/ingest/v1/job.proto

// The ingest queue, which is the path a caller takes when it does not want
// to wait. IngestService.Ingest is the other one: it streams, and the caller
// watches.
package ingestv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/bamsammich/docsearch/internal/api/docsearch/ingest/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// JobServiceName is the fully-qualified name of the JobService service.
	JobServiceName = "docsearch.ingest.v1.JobService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// JobServiceEnqueueProcedure is the fully-qualified name of the JobService's Enqueue RPC.
	JobServiceEnqueueProcedure = "/docsearch.ingest.v1.JobService/Enqueue"
	// JobServiceListJobsProcedure is the fully-qualified name of the JobService's ListJobs RPC.
	JobServiceListJobsProcedure = "/docsearch.ingest.v1.JobService/ListJobs"
	// JobServiceCancelJobProcedure is the fully-qualified name of the JobService's CancelJob RPC.
	JobServiceCancelJobProcedure = "/docsearch.ingest.v1.JobService/CancelJob"
)

// JobServiceClient is a client for the docsearch.ingest.v1.JobService service.
type JobServiceClient interface {
	// Enqueue puts one source on the queue for the worker.
	Enqueue(context.Context, *connect.Request[v1.EnqueueRequest]) (*connect.Response[v1.EnqueueResponse], error)
	// ListJobs is the queue, newest first.
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	// CancelJob asks a running job to stop. The worker notices between
	// progress writes and removes whatever the job half wrote.
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error)
}

// NewJobServiceClient constructs a client for the docsearch.ingest.v1.JobService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewJobServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) JobServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	jobServiceMethods := v1.File_docsearch_ingest_v1_job_proto.Services().ByName("JobService").Methods()
	return &jobServiceClient{
		enqueue: connect.NewClient[v1.EnqueueRequest, v1.EnqueueResponse](
			httpClient,
			baseURL+JobServiceEnqueueProcedure,
			connect.WithSchema(jobServiceMethods.ByName("Enqueue")),
			connect.WithClientOptions(opts...),
		),
		listJobs: connect.NewClient[v1.ListJobsRequest, v1.ListJobsResponse](
			httpClient,
			baseURL+JobServiceListJobsProcedure,
			connect.WithSchema(jobServiceMethods.ByName("ListJobs")),
			connect.WithClientOptions(opts...),
		),
		cancelJob: connect.NewClient[v1.CancelJobRequest, v1.CancelJobResponse](
			httpClient,
			baseURL+JobServiceCancelJobProcedure,
			connect.WithSchema(jobServiceMethods.ByName("CancelJob")),
			connect.WithClientOptions(opts...),
		),
	}
}

// jobServiceClient implements JobServiceClient.
type jobServiceClient struct {
	enqueue   *connect.Client[v1.EnqueueRequest, v1.EnqueueResponse]
	listJobs  *connect.Client[v1.ListJobsRequest, v1.ListJobsResponse]
	cancelJob *connect.Client[v1.CancelJobRequest, v1.CancelJobResponse]
}

// Enqueue calls docsearch.ingest.v1.JobService.Enqueue.
func (c *jobServiceClient) Enqueue(ctx context.Context, req *connect.Request[v1.EnqueueRequest]) (*connect.Response[v1.EnqueueResponse], error) {
	return c.enqueue.CallUnary(ctx, req)
}

// ListJobs calls docsearch.ingest.v1.JobService.ListJobs.
func (c *jobServiceClient) ListJobs(ctx context.Context, req *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return c.listJobs.CallUnary(ctx, req)
}

// CancelJob calls docsearch.ingest.v1.JobService.CancelJob.
func (c *jobServiceClient) CancelJob(ctx context.Context, req *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error) {
	return c.cancelJob.CallUnary(ctx, req)
}

// JobServiceHandler is an implementation of the docsearch.ingest.v1.JobService service.
type JobServiceHandler interface {
	// Enqueue puts one source on the queue for the worker.
	Enqueue(context.Context, *connect.Request[v1.EnqueueRequest]) (*connect.Response[v1.EnqueueResponse], error)
	// ListJobs is the queue, newest first.
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	// CancelJob asks a running job to stop. The worker notices between
	// progress writes and removes whatever the job half wrote.
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error)
}

// NewJobServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewJobServiceHandler(svc JobServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	jobServiceMethods := v1.File_docsearch_ingest_v1_job_proto.Services().ByName("JobService").Methods()
	jobServiceEnqueueHandler := connect.NewUnaryHandler(
		JobServiceEnqueueProcedure,
		svc.Enqueue,
		connect.WithSchema(jobServiceMethods.ByName("Enqueue")),
		connect.WithHandlerOptions(opts...),
	)
	jobServiceListJobsHandler := connect.NewUnaryHandler(
		JobServiceListJobsProcedure,
		svc.ListJobs,
		connect.WithSchema(jobServiceMethods.ByName("ListJobs")),
		connect.WithHandlerOptions(opts...),
	)
	jobServiceCancelJobHandler := connect.NewUnaryHandler(
		JobServiceCancelJobProcedure,
		svc.CancelJob,
		connect.WithSchema(jobServiceMethods.ByName("CancelJob")),
		connect.WithHandlerOptions(opts...),
	)
	return "/docsearch.ingest.v1.JobService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case JobServiceEnqueueProcedure:
			jobServiceEnqueueHandler.ServeHTTP(w, r)
		case JobServiceListJobsProcedure:
			jobServiceListJobsHandler.ServeHTTP(w, r)
		case JobServiceCancelJobProcedure:
			jobServiceCancelJobHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedJobServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedJobServiceHandler struct{}

func (UnimplementedJobServiceHandler) Enqueue(context.Context, *connect.Request[v1.EnqueueRequest]) (*connect.Response[v1.EnqueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("docsearch.ingest.v1.JobService.Enqueue is not implemented"))
}

func (UnimplementedJobServiceHandler) ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("docsearch.ingest.v1.JobService.ListJobs is not implemented"))
}

func (UnimplementedJobServiceHandler) CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("docsearch.ingest.v1.JobService.CancelJob is not implemented"))
}
