// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package dbgen

import (
	"context"
	"database/sql"
)

const allChunksInOrder = `-- name: AllChunksInOrder :many
SELECT id, heading_path, text FROM chunks
 WHERE doc_id = ? ORDER BY ordinal
`

type AllChunksInOrderRow struct {
	ID          int64
	HeadingPath string
	Text        string
}

func (q *Queries) AllChunksInOrder(ctx context.Context, docID string) ([]AllChunksInOrderRow, error) {
	rows, err := q.db.QueryContext(ctx, allChunksInOrder, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AllChunksInOrderRow{}
	for rows.Next() {
		var i AllChunksInOrderRow
		if err := rows.Scan(&i.ID, &i.HeadingPath, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chunkOrdinal = `-- name: ChunkOrdinal :one
SELECT ordinal FROM chunks WHERE id = ? AND doc_id = ?
`

type ChunkOrdinalParams struct {
	ID    int64
	DocID string
}

func (q *Queries) ChunkOrdinal(ctx context.Context, arg ChunkOrdinalParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, chunkOrdinal, arg.ID, arg.DocID)
	var ordinal int64
	err := row.Scan(&ordinal)
	return ordinal, err
}

const chunksInSection = `-- name: ChunksInSection :many
SELECT heading_path, text FROM chunks
 WHERE doc_id = ? AND (chunks.section = ? OR chunks.section LIKE ? || '.%')
 ORDER BY ordinal
`

type ChunksInSectionParams struct {
	DocID   string
	Section sql.NullString
	Column3 sql.NullString
}

type ChunksInSectionRow struct {
	HeadingPath string
	Text        string
}

// Section references resolve component-wise, never by bare string prefix: a
// reference to "4" covers "4" and "4.1" and must not touch "41". The trailing
// dot is what makes it a boundary. Kept identical to store.SectionMatchSQL,
// which the in-memory index-term boost applies by the same rule.
func (q *Queries) ChunksInSection(ctx context.Context, arg ChunksInSectionParams) ([]ChunksInSectionRow, error) {
	rows, err := q.db.QueryContext(ctx, chunksInSection, arg.DocID, arg.Section, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChunksInSectionRow{}
	for rows.Next() {
		var i ChunksInSectionRow
		if err := rows.Scan(&i.HeadingPath, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const chunksMatchingHeading = `-- name: ChunksMatchingHeading :many
SELECT heading_path, text FROM chunks
 WHERE doc_id = ? AND lower(heading_path) LIKE '%' || lower(?) || '%'
 ORDER BY ordinal
`

type ChunksMatchingHeadingParams struct {
	DocID string
	LOWER string
}

type ChunksMatchingHeadingRow struct {
	HeadingPath string
	Text        string
}

func (q *Queries) ChunksMatchingHeading(ctx context.Context, arg ChunksMatchingHeadingParams) ([]ChunksMatchingHeadingRow, error) {
	rows, err := q.db.QueryContext(ctx, chunksMatchingHeading, arg.DocID, arg.LOWER)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChunksMatchingHeadingRow{}
	for rows.Next() {
		var i ChunksMatchingHeadingRow
		if err := rows.Scan(&i.HeadingPath, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contextChunks = `-- name: ContextChunks :many
SELECT id, ordinal, heading_path, section, page_start, image_count, url, fragment, text
  FROM chunks
 WHERE doc_id = ? AND ordinal BETWEEN ? AND ?
 ORDER BY ordinal
`

type ContextChunksRow struct {
	ID          int64
	Ordinal     int64
	HeadingPath string
	Section     sql.NullString
	PageStart   sql.NullInt64
	ImageCount  int64
	Url         sql.NullString
	Fragment    sql.NullString
	Text        string
}

func (q *Queries) ContextChunks(ctx context.Context, docID string) ([]ContextChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, contextChunks, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContextChunksRow{}
	for rows.Next() {
		var i ContextChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.Ordinal,
			&i.HeadingPath,
			&i.Section,
			&i.PageStart,
			&i.ImageCount,
			&i.Url,
			&i.Fragment,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const outlineRows = `-- name: OutlineRows :many
SELECT id, section, page_start, heading_path
  FROM chunks WHERE doc_id = ? ORDER BY ordinal
`

type OutlineRowsRow struct {
	ID          int64
	Section     sql.NullString
	PageStart   sql.NullInt64
	HeadingPath string
}

func (q *Queries) OutlineRows(ctx context.Context, docID string) ([]OutlineRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, outlineRows, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutlineRowsRow{}
	for rows.Next() {
		var i OutlineRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Section,
			&i.PageStart,
			&i.HeadingPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pagesInRange = `-- name: PagesInRange :many
SELECT page, text FROM pages
 WHERE doc_id = ? AND page BETWEEN ? AND ?
 ORDER BY page
`

type PagesInRangeRow struct {
	Page int64
	Text string
}

func (q *Queries) PagesInRange(ctx context.Context, docID string) ([]PagesInRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, pagesInRange, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PagesInRangeRow{}
	for rows.Next() {
		var i PagesInRangeRow
		if err := rows.Scan(&i.Page, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topLevelHeadings = `-- name: TopLevelHeadings :many
SELECT DISTINCT heading_path FROM chunks
 WHERE doc_id = ? AND heading_path <> ''
 ORDER BY ordinal
`

func (q *Queries) TopLevelHeadings(ctx context.Context, docID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, topLevelHeadings, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var heading_path string
		if err := rows.Scan(&heading_path); err != nil {
			return nil, err
		}
		items = append(items, heading_path)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
