// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package dbgen

import (
	"context"
	"database/sql"
)

const completeJob = `-- name: CompleteJob :exec
UPDATE ingest_jobs
   SET status = 'done', phase = NULL, doc_id = ?, error = NULL, warnings = ?,
       lease_until = NULL, updated_at = datetime('now')
 WHERE id = ?
`

type CompleteJobParams struct {
	DocID    sql.NullString
	Warnings sql.NullString
	ID       int64
}

// Run in the same transaction as MarkDocumentReady, so a document can never
// be searchable while the job that wrote it still reads as running.
func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) error {
	_, err := q.db.ExecContext(ctx, completeJob, arg.DocID, arg.Warnings, arg.ID)
	return err
}

const countDocumentChunks = `-- name: CountDocumentChunks :one
SELECT COUNT(*) FROM chunks WHERE doc_id = ?
`

func (q *Queries) CountDocumentChunks(ctx context.Context, docID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDocumentChunks, docID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDocumentChunks = `-- name: DeleteDocumentChunks :exec
DELETE FROM chunks WHERE doc_id = ?
`

// Ordering matters. The AFTER DELETE trigger on chunks is what clears
// chunks_fts, so chunks go through SQL rather than a bulk drop, and they go
// first: deleting the document row first would take them with it through the
// foreign key, without the trigger.
func (q *Queries) DeleteDocumentChunks(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentChunks, docID)
	return err
}

const deleteDocumentIndexTerms = `-- name: DeleteDocumentIndexTerms :exec
DELETE FROM index_terms WHERE doc_id = ?
`

func (q *Queries) DeleteDocumentIndexTerms(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentIndexTerms, docID)
	return err
}

const deleteDocumentPages = `-- name: DeleteDocumentPages :exec
DELETE FROM pages WHERE doc_id = ?
`

func (q *Queries) DeleteDocumentPages(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentPages, docID)
	return err
}

const deleteDocumentRow = `-- name: DeleteDocumentRow :exec
DELETE FROM documents WHERE doc_id = ?
`

func (q *Queries) DeleteDocumentRow(ctx context.Context, docID string) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentRow, docID)
	return err
}

const docIDForSourcePath = `-- name: DocIDForSourcePath :one
SELECT doc_id FROM documents WHERE source_path = ?
`

func (q *Queries) DocIDForSourcePath(ctx context.Context, sourcePath string) (string, error) {
	row := q.db.QueryRowContext(ctx, docIDForSourcePath, sourcePath)
	var doc_id string
	err := row.Scan(&doc_id)
	return doc_id, err
}

const docIDsWithPrefix = `-- name: DocIDsWithPrefix :many
SELECT doc_id FROM documents WHERE doc_id LIKE ?
`

func (q *Queries) DocIDsWithPrefix(ctx context.Context, docID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, docIDsWithPrefix, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var doc_id string
		if err := rows.Scan(&doc_id); err != nil {
			return nil, err
		}
		items = append(items, doc_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const documentByID = `-- name: DocumentByID :one
SELECT doc_id, title, format, source_kind, status, page_count, chunk_count, warnings
  FROM documents WHERE doc_id = ?
`

type DocumentByIDRow struct {
	DocID      string
	Title      string
	Format     string
	SourceKind string
	Status     string
	PageCount  sql.NullInt64
	ChunkCount sql.NullInt64
	Warnings   sql.NullString
}

func (q *Queries) DocumentByID(ctx context.Context, docID string) (DocumentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, documentByID, docID)
	var i DocumentByIDRow
	err := row.Scan(
		&i.DocID,
		&i.Title,
		&i.Format,
		&i.SourceKind,
		&i.Status,
		&i.PageCount,
		&i.ChunkCount,
		&i.Warnings,
	)
	return i, err
}

const documentChunks = `-- name: DocumentChunks :many
SELECT ordinal, section, page_start, page_end, printed_page_start,
       image_count, kind, url, fragment, heading_path, text
  FROM chunks
 WHERE doc_id = ?
 ORDER BY ordinal
`

type DocumentChunksRow struct {
	Ordinal          int64
	Section          sql.NullString
	PageStart        sql.NullInt64
	PageEnd          sql.NullInt64
	PrintedPageStart sql.NullInt64
	ImageCount       int64
	Kind             string
	Url              sql.NullString
	Fragment         sql.NullString
	HeadingPath      string
	Text             string
}

// Verification reads every column, because what it checks is whether the
// columns agree with each other.
func (q *Queries) DocumentChunks(ctx context.Context, docID string) ([]DocumentChunksRow, error) {
	rows, err := q.db.QueryContext(ctx, documentChunks, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentChunksRow{}
	for rows.Next() {
		var i DocumentChunksRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.Section,
			&i.PageStart,
			&i.PageEnd,
			&i.PrintedPageStart,
			&i.ImageCount,
			&i.Kind,
			&i.Url,
			&i.Fragment,
			&i.HeadingPath,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const indexTermSections = `-- name: IndexTermSections :many
SELECT DISTINCT section FROM index_terms WHERE doc_id = ? ORDER BY section
`

func (q *Queries) IndexTermSections(ctx context.Context, docID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, indexTermSections, docID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var section string
		if err := rows.Scan(&section); err != nil {
			return nil, err
		}
		items = append(items, section)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChunk = `-- name: InsertChunk :exec
INSERT INTO chunks (
  doc_id, ordinal, section, page_start, page_end, printed_page_start,
  image_count, kind, url, fragment, heading_path, text
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertChunkParams struct {
	DocID            string
	Ordinal          int64
	Section          sql.NullString
	PageStart        sql.NullInt64
	PageEnd          sql.NullInt64
	PrintedPageStart sql.NullInt64
	ImageCount       int64
	Kind             string
	Url              sql.NullString
	Fragment         sql.NullString
	HeadingPath      string
	Text             string
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) error {
	_, err := q.db.ExecContext(ctx, insertChunk,
		arg.DocID,
		arg.Ordinal,
		arg.Section,
		arg.PageStart,
		arg.PageEnd,
		arg.PrintedPageStart,
		arg.ImageCount,
		arg.Kind,
		arg.Url,
		arg.Fragment,
		arg.HeadingPath,
		arg.Text,
	)
	return err
}

const insertDocument = `-- name: InsertDocument :exec
INSERT INTO documents (
  doc_id, title, format, source_path, source_kind, sha256,
  page_count, chunk_count, status, ingested_at
) VALUES (?, ?, ?, ?, ?, ?, ?, NULL, 'ingesting', NULL)
`

type InsertDocumentParams struct {
	DocID      string
	Title      string
	Format     string
	SourcePath string
	SourceKind string
	Sha256     string
	PageCount  sql.NullInt64
}

// A document is born 'ingesting' with no chunk count and no timestamp, so
// every read path, which filters on status = 'ready', passes over it until
// MarkDocumentReady runs.
func (q *Queries) InsertDocument(ctx context.Context, arg InsertDocumentParams) error {
	_, err := q.db.ExecContext(ctx, insertDocument,
		arg.DocID,
		arg.Title,
		arg.Format,
		arg.SourcePath,
		arg.SourceKind,
		arg.Sha256,
		arg.PageCount,
	)
	return err
}

const insertIndexTerm = `-- name: InsertIndexTerm :exec
INSERT INTO index_terms (doc_id, term, section) VALUES (?, ?, ?)
`

type InsertIndexTermParams struct {
	DocID   string
	Term    string
	Section string
}

func (q *Queries) InsertIndexTerm(ctx context.Context, arg InsertIndexTermParams) error {
	_, err := q.db.ExecContext(ctx, insertIndexTerm, arg.DocID, arg.Term, arg.Section)
	return err
}

const markDocumentReady = `-- name: MarkDocumentReady :exec
UPDATE documents
   SET status = 'ready', chunk_count = ?, ingested_at = ?, warnings = ?
 WHERE doc_id = ?
`

type MarkDocumentReadyParams struct {
	ChunkCount sql.NullInt64
	IngestedAt sql.NullString
	Warnings   sql.NullString
	DocID      string
}

// The moment a document becomes visible to search.
func (q *Queries) MarkDocumentReady(ctx context.Context, arg MarkDocumentReadyParams) error {
	_, err := q.db.ExecContext(ctx, markDocumentReady,
		arg.ChunkCount,
		arg.IngestedAt,
		arg.Warnings,
		arg.DocID,
	)
	return err
}

const readyDocumentWithDigest = `-- name: ReadyDocumentWithDigest :one

SELECT doc_id, title FROM documents WHERE sha256 = ? AND status = 'ready'
`

type ReadyDocumentWithDigestRow struct {
	DocID string
	Title string
}

// Writes the ingest service makes, through internal/repository/sqlite.
//
// Reads the server makes live in documents.sql, chunks.sql and jobs.sql. The
// split is by who runs the statement, not by which table it names: the worker
// writes a document incrementally and the server must not see it until the
// last statement here flips its status.
func (q *Queries) ReadyDocumentWithDigest(ctx context.Context, sha256 string) (ReadyDocumentWithDigestRow, error) {
	row := q.db.QueryRowContext(ctx, readyDocumentWithDigest, sha256)
	var i ReadyDocumentWithDigestRow
	err := row.Scan(&i.DocID, &i.Title)
	return i, err
}

const sectionHasChunks = `-- name: SectionHasChunks :one
SELECT EXISTS(
  SELECT 1 FROM chunks
   WHERE doc_id = ? AND (chunks.section = ? OR chunks.section LIKE ? || '.%'))
`

type SectionHasChunksParams struct {
	DocID   string
	Section sql.NullString
	Column3 sql.NullString
}

// Subtree semantics, the same clause ChunksInSection uses: an index entry
// pointing at chapter 4 refers to the whole chapter.
func (q *Queries) SectionHasChunks(ctx context.Context, arg SectionHasChunksParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, sectionHasChunks, arg.DocID, arg.Section, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertPage = `-- name: UpsertPage :exec
INSERT OR REPLACE INTO pages (doc_id, page, text) VALUES (?, ?, ?)
`

type UpsertPageParams struct {
	DocID string
	Page  int64
	Text  string
}

func (q *Queries) UpsertPage(ctx context.Context, arg UpsertPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertPage, arg.DocID, arg.Page, arg.Text)
	return err
}
