// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package dbgen

import (
	"context"
	"database/sql"
)

const activeJobs = `-- name: ActiveJobs :many
SELECT id, source_path, title, doc_id, status, phase, progress_cur, progress_tot, attempts, permanent, cancel_req, error, warnings, lease_until, created_at, updated_at FROM ingest_jobs
 WHERE status IN ('queued','running')
 ORDER BY created_at, id
`

func (q *Queries) ActiveJobs(ctx context.Context) ([]IngestJob, error) {
	rows, err := q.db.QueryContext(ctx, activeJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestJob{}
	for rows.Next() {
		var i IngestJob
		if err := rows.Scan(
			&i.ID,
			&i.SourcePath,
			&i.Title,
			&i.DocID,
			&i.Status,
			&i.Phase,
			&i.ProgressCur,
			&i.ProgressTot,
			&i.Attempts,
			&i.Permanent,
			&i.CancelReq,
			&i.Error,
			&i.Warnings,
			&i.LeaseUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueJob = `-- name: EnqueueJob :execresult
INSERT INTO ingest_jobs (source_path, title, status, created_at, updated_at)
VALUES (?, ?, 'queued', datetime('now'), datetime('now'))
`

type EnqueueJobParams struct {
	SourcePath string
	Title      sql.NullString
}

func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, enqueueJob, arg.SourcePath, arg.Title)
}

const jobByID = `-- name: JobByID :one
SELECT id, source_path, title, doc_id, status, phase, progress_cur, progress_tot, attempts, permanent, cancel_req, error, warnings, lease_until, created_at, updated_at FROM ingest_jobs WHERE id = ?
`

// The three job reads select * so they share one generated row type and one
// mapper. Column-order drift, the usual reason to avoid *, is what sqlc
// removes: the struct and the scan are generated from the schema together.
func (q *Queries) JobByID(ctx context.Context, id int64) (IngestJob, error) {
	row := q.db.QueryRowContext(ctx, jobByID, id)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.Title,
		&i.DocID,
		&i.Status,
		&i.Phase,
		&i.ProgressCur,
		&i.ProgressTot,
		&i.Attempts,
		&i.Permanent,
		&i.CancelReq,
		&i.Error,
		&i.Warnings,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const jobStatus = `-- name: JobStatus :one
SELECT status FROM ingest_jobs WHERE id = ?
`

func (q *Queries) JobStatus(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, jobStatus, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const queuePosition = `-- name: QueuePosition :one
SELECT COUNT(*) FROM ingest_jobs
 WHERE status IN ('queued','running') AND id <= ?
`

// Position counts the job itself, so a freshly queued job with nothing ahead
// of it reports 1 rather than 0.
func (q *Queries) QueuePosition(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, queuePosition, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recentJobs = `-- name: RecentJobs :many
SELECT id, source_path, title, doc_id, status, phase, progress_cur, progress_tot, attempts, permanent, cancel_req, error, warnings, lease_until, created_at, updated_at FROM ingest_jobs
 ORDER BY (status IN ('queued','running')) DESC, updated_at DESC
 LIMIT ?
`

func (q *Queries) RecentJobs(ctx context.Context, limit int64) ([]IngestJob, error) {
	rows, err := q.db.QueryContext(ctx, recentJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestJob{}
	for rows.Next() {
		var i IngestJob
		if err := rows.Scan(
			&i.ID,
			&i.SourcePath,
			&i.Title,
			&i.DocID,
			&i.Status,
			&i.Phase,
			&i.ProgressCur,
			&i.ProgressTot,
			&i.Attempts,
			&i.Permanent,
			&i.CancelReq,
			&i.Error,
			&i.Warnings,
			&i.LeaseUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestJobCancel = `-- name: RequestJobCancel :exec
UPDATE ingest_jobs SET cancel_req = 1, updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) RequestJobCancel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, requestJobCancel, id)
	return err
}
