// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
)

type Chunk struct {
	ID               int64
	DocID            string
	Ordinal          int64
	Section          sql.NullString
	PageStart        sql.NullInt64
	PageEnd          sql.NullInt64
	PrintedPageStart sql.NullInt64
	ImageCount       int64
	Kind             string
	Url              sql.NullString
	Fragment         sql.NullString
	HeadingPath      string
	Text             string
}

type ChunksFt struct {
	Text        string
	HeadingPath string
	DocID       string
}

type Document struct {
	DocID      string
	Title      string
	Format     string
	SourcePath string
	SourceKind string
	Sha256     string
	PageCount  sql.NullInt64
	ChunkCount sql.NullInt64
	Status     string
	IngestedAt sql.NullString
	Warnings   sql.NullString
}

type IndexTerm struct {
	DocID   string
	Term    string
	Section string
}

type IngestJob struct {
	ID          int64
	SourcePath  string
	Title       sql.NullString
	DocID       sql.NullString
	Status      string
	Phase       sql.NullString
	ProgressCur sql.NullInt64
	ProgressTot sql.NullInt64
	Attempts    int64
	Permanent   int64
	CancelReq   int64
	Error       sql.NullString
	Warnings    sql.NullString
	LeaseUntil  sql.NullString
	CreatedAt   string
	UpdatedAt   string
}

type Page struct {
	DocID string
	Page  int64
	Text  string
}

type SchemaVersion struct {
	Version   int64
	AppliedAt string
}
