// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package dbgen

import (
	"context"
	"database/sql"
)

const cancelJob = `-- name: CancelJob :exec
UPDATE ingest_jobs
   SET status = 'cancelled', phase = NULL, lease_until = NULL,
       error = 'cancelled at operator request', updated_at = datetime('now')
 WHERE id = ?
`

func (q *Queries) CancelJob(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, cancelJob, id)
	return err
}

const claimJob = `-- name: ClaimJob :one

UPDATE ingest_jobs
   SET status = 'running',
       attempts = attempts + 1,
       phase = NULL,
       progress_cur = NULL,
       progress_tot = NULL,
       error = NULL,
       lease_until = datetime('now', ?),
       updated_at = datetime('now')
 WHERE id = (
       SELECT next.id FROM ingest_jobs next
        WHERE next.cancel_req = 0
          AND next.attempts < ?
          AND (next.status = 'queued'
               OR (next.status = 'running' AND next.lease_until < datetime('now')))
        ORDER BY next.created_at, next.id
        LIMIT 1)
RETURNING id, source_path, title, doc_id, status, phase, progress_cur, progress_tot, attempts, permanent, cancel_req, error, warnings, lease_until, created_at, updated_at
`

type ClaimJobParams struct {
	Datetime interface{}
	Attempts int64
}

// The worker's job statements, through internal/repository/sqlite.
//
// Crash recovery rests on the lease. A claimed job carries lease_until, and
// the claim takes back any running job whose lease has expired, so a worker
// killed mid-job is recovered by the next one without intervention.
// Claims one job. A single statement, so two workers racing cannot take the
// same row.
//
// Jobs at or past the attempt ceiling are excluded here rather than after
// claiming: a permanently failing job that is claimed and then put back would
// be reclaimed forever and starve the queue.
func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (IngestJob, error) {
	row := q.db.QueryRowContext(ctx, claimJob, arg.Datetime, arg.Attempts)
	var i IngestJob
	err := row.Scan(
		&i.ID,
		&i.SourcePath,
		&i.Title,
		&i.DocID,
		&i.Status,
		&i.Phase,
		&i.ProgressCur,
		&i.ProgressTot,
		&i.Attempts,
		&i.Permanent,
		&i.CancelReq,
		&i.Error,
		&i.Warnings,
		&i.LeaseUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeJobWithoutDocument = `-- name: CompleteJobWithoutDocument :exec
UPDATE ingest_jobs
   SET status = 'done', phase = NULL, doc_id = ?, error = NULL,
       lease_until = NULL, updated_at = datetime('now')
 WHERE id = ?
`

type CompleteJobWithoutDocumentParams struct {
	DocID sql.NullString
	ID    int64
}

// Completes a job whose ingest wrote nothing, which is what an unchanged
// source produces: the transaction that would have completed the job
// alongside the document never ran, because no document was written.
func (q *Queries) CompleteJobWithoutDocument(ctx context.Context, arg CompleteJobWithoutDocumentParams) error {
	_, err := q.db.ExecContext(ctx, completeJobWithoutDocument, arg.DocID, arg.ID)
	return err
}

const finishJob = `-- name: FinishJob :exec
UPDATE ingest_jobs
   SET status = ?, phase = NULL, error = ?, permanent = ?,
       lease_until = NULL, updated_at = datetime('now')
 WHERE id = ?
`

type FinishJobParams struct {
	Status    string
	Error     sql.NullString
	Permanent int64
	ID        int64
}

// attempts is left at its true value. A status of 'failed' is already
// unclaimable, since the claim considers only 'queued' and lease-expired
// 'running', so inflating the counter to block a reclaim would buy nothing
// and would make a job that failed deterministically on its first attempt
// indistinguishable from one that genuinely exhausted three. The permanent
// flag carries that distinction instead.
func (q *Queries) FinishJob(ctx context.Context, arg FinishJobParams) error {
	_, err := q.db.ExecContext(ctx, finishJob,
		arg.Status,
		arg.Error,
		arg.Permanent,
		arg.ID,
	)
	return err
}

const jobCancelRequested = `-- name: JobCancelRequested :one
SELECT cancel_req FROM ingest_jobs WHERE id = ?
`

func (q *Queries) JobCancelRequested(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, jobCancelRequested, id)
	var cancel_req int64
	err := row.Scan(&cancel_req)
	return cancel_req, err
}

const jobDocID = `-- name: JobDocID :one
SELECT doc_id FROM ingest_jobs WHERE id = ?
`

func (q *Queries) JobDocID(ctx context.Context, id int64) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, jobDocID, id)
	var doc_id sql.NullString
	err := row.Scan(&doc_id)
	return doc_id, err
}

const recordJobDocID = `-- name: RecordJobDocID :exec
UPDATE ingest_jobs
   SET doc_id = ?, updated_at = datetime('now')
 WHERE id = ?
`

type RecordJobDocIDParams struct {
	DocID sql.NullString
	ID    int64
}

// Recorded while the ingest runs, so a job that dies mid-write still says
// which document it was writing.
func (q *Queries) RecordJobDocID(ctx context.Context, arg RecordJobDocIDParams) error {
	_, err := q.db.ExecContext(ctx, recordJobDocID, arg.DocID, arg.ID)
	return err
}

const recordJobProgress = `-- name: RecordJobProgress :exec
UPDATE ingest_jobs
   SET phase = ?, progress_cur = ?, progress_tot = ?,
       lease_until = datetime('now', ?), updated_at = datetime('now')
 WHERE id = ?
`

type RecordJobProgressParams struct {
	Phase       sql.NullString
	ProgressCur sql.NullInt64
	ProgressTot sql.NullInt64
	Datetime    interface{}
	ID          int64
}

// Every progress write renews the lease: a job that is visibly advancing must
// never be reclaimed out from under the worker running it.
func (q *Queries) RecordJobProgress(ctx context.Context, arg RecordJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, recordJobProgress,
		arg.Phase,
		arg.ProgressCur,
		arg.ProgressTot,
		arg.Datetime,
		arg.ID,
	)
	return err
}
